<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CedulaCumplimientoTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cedula_cumplimiento')->delete();
        
        \DB::table('cedula_cumplimiento')->insert(array (
            0 => 
            array (
                'autorizo' => '',
                'contrato_id' => 1,
                'created_at' => '2022-02-15 15:23:07',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 1,
                'reviso' => '',
                'updated_at' => '2022-02-15 15:23:07',
            ),
            1 => 
            array (
                'autorizo' => '',
                'contrato_id' => 2,
                'created_at' => '2022-02-18 10:38:36',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 2,
                'reviso' => '',
                'updated_at' => '2022-02-18 10:38:36',
            ),
            2 => 
            array (
                'autorizo' => '',
                'contrato_id' => 3,
                'created_at' => '2022-02-18 18:17:49',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 3,
                'reviso' => '',
                'updated_at' => '2022-02-18 18:17:49',
            ),
            3 => 
            array (
                'autorizo' => '',
                'contrato_id' => 4,
                'created_at' => '2022-02-18 18:53:52',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 4,
                'reviso' => '',
                'updated_at' => '2022-02-18 18:53:52',
            ),
            4 => 
            array (
                'autorizo' => '',
                'contrato_id' => 8,
                'created_at' => '2022-03-10 15:46:01',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 5,
                'reviso' => '',
                'updated_at' => '2022-03-10 15:46:01',
            ),
            5 => 
            array (
                'autorizo' => '',
                'contrato_id' => 9,
                'created_at' => '2022-03-15 16:10:11',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 6,
                'reviso' => '',
                'updated_at' => '2022-03-15 16:10:11',
            ),
            6 => 
            array (
                'autorizo' => '',
                'contrato_id' => 10,
                'created_at' => '2022-04-05 15:23:00',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 7,
                'reviso' => '',
                'updated_at' => '2022-04-05 15:23:00',
            ),
            7 => 
            array (
                'autorizo' => '',
                'contrato_id' => 11,
                'created_at' => '2022-04-07 13:08:47',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 8,
                'reviso' => '',
                'updated_at' => '2022-04-07 13:08:47',
            ),
            8 => 
            array (
                'autorizo' => '',
                'contrato_id' => 12,
                'created_at' => '2022-04-14 23:17:18',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 9,
                'reviso' => '',
                'updated_at' => '2022-04-14 23:17:18',
            ),
            9 => 
            array (
                'autorizo' => '',
                'contrato_id' => 13,
                'created_at' => '2022-04-19 10:49:55',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 10,
                'reviso' => '',
                'updated_at' => '2022-04-19 10:49:55',
            ),
            10 => 
            array (
                'autorizo' => '',
                'contrato_id' => 14,
                'created_at' => '2022-04-19 17:23:52',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 11,
                'reviso' => '',
                'updated_at' => '2022-04-19 17:23:52',
            ),
            11 => 
            array (
                'autorizo' => '',
                'contrato_id' => 15,
                'created_at' => '2022-04-22 17:27:16',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 12,
                'reviso' => '',
                'updated_at' => '2022-04-22 17:27:16',
            ),
            12 => 
            array (
                'autorizo' => '',
                'contrato_id' => 16,
                'created_at' => '2022-04-26 14:57:55',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 13,
                'reviso' => '',
                'updated_at' => '2022-04-26 14:57:55',
            ),
            13 => 
            array (
                'autorizo' => '',
                'contrato_id' => 17,
                'created_at' => '2022-05-05 13:42:48',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 14,
                'reviso' => '',
                'updated_at' => '2022-05-05 13:42:48',
            ),
            14 => 
            array (
                'autorizo' => '',
                'contrato_id' => 18,
                'created_at' => '2022-05-13 17:43:28',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 15,
                'reviso' => '',
                'updated_at' => '2022-05-13 17:43:28',
            ),
            15 => 
            array (
                'autorizo' => '',
                'contrato_id' => 19,
                'created_at' => '2022-05-13 17:56:22',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 16,
                'reviso' => '',
                'updated_at' => '2022-05-13 17:56:22',
            ),
            16 => 
            array (
                'autorizo' => '',
                'contrato_id' => 20,
                'created_at' => '2022-05-13 18:43:29',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 17,
                'reviso' => '',
                'updated_at' => '2022-05-13 18:43:29',
            ),
            17 => 
            array (
                'autorizo' => '',
                'contrato_id' => 21,
                'created_at' => '2022-05-16 14:40:08',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 18,
                'reviso' => '',
                'updated_at' => '2022-05-16 14:40:08',
            ),
            18 => 
            array (
                'autorizo' => '',
                'contrato_id' => 23,
                'created_at' => '2022-05-17 14:34:40',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 19,
                'reviso' => '',
                'updated_at' => '2022-05-17 14:34:40',
            ),
            19 => 
            array (
                'autorizo' => '',
                'contrato_id' => 25,
                'created_at' => '2022-05-17 15:02:24',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 20,
                'reviso' => '',
                'updated_at' => '2022-05-17 15:02:24',
            ),
            20 => 
            array (
                'autorizo' => '',
                'contrato_id' => 26,
                'created_at' => '2022-05-18 12:52:37',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 21,
                'reviso' => '',
                'updated_at' => '2022-05-18 12:52:37',
            ),
            21 => 
            array (
                'autorizo' => '',
                'contrato_id' => 27,
                'created_at' => '2022-05-18 12:57:49',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 22,
                'reviso' => '',
                'updated_at' => '2022-05-18 12:57:49',
            ),
            22 => 
            array (
                'autorizo' => '',
                'contrato_id' => 28,
                'created_at' => '2022-05-18 13:44:28',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 23,
                'reviso' => '',
                'updated_at' => '2022-05-18 13:44:28',
            ),
            23 => 
            array (
                'autorizo' => '',
                'contrato_id' => 29,
                'created_at' => '2022-05-18 13:48:18',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 24,
                'reviso' => '',
                'updated_at' => '2022-05-18 13:48:18',
            ),
            24 => 
            array (
                'autorizo' => '',
                'contrato_id' => 30,
                'created_at' => '2022-05-18 14:26:13',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 25,
                'reviso' => '',
                'updated_at' => '2022-05-18 14:26:13',
            ),
            25 => 
            array (
                'autorizo' => '',
                'contrato_id' => 31,
                'created_at' => '2022-05-19 10:31:27',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 26,
                'reviso' => '',
                'updated_at' => '2022-05-19 10:31:27',
            ),
            26 => 
            array (
                'autorizo' => '',
                'contrato_id' => 32,
                'created_at' => '2022-05-26 15:43:04',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 27,
                'reviso' => '',
                'updated_at' => '2022-05-26 15:43:04',
            ),
            27 => 
            array (
                'autorizo' => '',
                'contrato_id' => 33,
                'created_at' => '2022-06-07 10:29:56',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 28,
                'reviso' => '',
                'updated_at' => '2022-06-07 10:29:56',
            ),
            28 => 
            array (
                'autorizo' => '',
                'contrato_id' => 34,
                'created_at' => '2022-06-08 17:03:02',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 29,
                'reviso' => '',
                'updated_at' => '2022-06-08 17:03:02',
            ),
            29 => 
            array (
                'autorizo' => '',
                'contrato_id' => 35,
                'created_at' => '2022-06-08 17:21:59',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 30,
                'reviso' => '',
                'updated_at' => '2022-06-08 17:21:59',
            ),
            30 => 
            array (
                'autorizo' => '',
                'contrato_id' => 36,
                'created_at' => '2022-06-08 17:40:38',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 31,
                'reviso' => '',
                'updated_at' => '2022-06-08 17:40:38',
            ),
            31 => 
            array (
                'autorizo' => '',
                'contrato_id' => 37,
                'created_at' => '2022-06-09 08:23:11',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 32,
                'reviso' => '',
                'updated_at' => '2022-06-09 08:23:11',
            ),
            32 => 
            array (
                'autorizo' => '',
                'contrato_id' => 38,
                'created_at' => '2022-06-09 08:45:53',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 33,
                'reviso' => '',
                'updated_at' => '2022-06-09 08:45:53',
            ),
            33 => 
            array (
                'autorizo' => '',
                'contrato_id' => 39,
                'created_at' => '2022-06-09 09:00:55',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 34,
                'reviso' => '',
                'updated_at' => '2022-06-09 09:00:55',
            ),
            34 => 
            array (
                'autorizo' => '',
                'contrato_id' => 40,
                'created_at' => '2022-06-09 09:55:48',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 35,
                'reviso' => '',
                'updated_at' => '2022-06-09 09:55:48',
            ),
            35 => 
            array (
                'autorizo' => '',
                'contrato_id' => 41,
                'created_at' => '2022-06-10 10:02:09',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 36,
                'reviso' => '',
                'updated_at' => '2022-06-10 10:02:09',
            ),
            36 => 
            array (
                'autorizo' => '',
                'contrato_id' => 42,
                'created_at' => '2022-06-15 11:01:58',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 37,
                'reviso' => '',
                'updated_at' => '2022-06-15 11:01:58',
            ),
            37 => 
            array (
                'autorizo' => '',
                'contrato_id' => 43,
                'created_at' => '2022-06-15 12:07:41',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 38,
                'reviso' => '',
                'updated_at' => '2022-06-15 12:07:41',
            ),
            38 => 
            array (
                'autorizo' => '',
                'contrato_id' => 47,
                'created_at' => '2022-06-27 11:05:27',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 39,
                'reviso' => '',
                'updated_at' => '2022-06-27 11:05:27',
            ),
            39 => 
            array (
                'autorizo' => '',
                'contrato_id' => 48,
                'created_at' => '2022-06-27 13:52:16',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 40,
                'reviso' => '',
                'updated_at' => '2022-06-27 13:52:16',
            ),
            40 => 
            array (
                'autorizo' => '',
                'contrato_id' => 49,
                'created_at' => '2022-06-27 15:25:03',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 41,
                'reviso' => '',
                'updated_at' => '2022-06-27 15:25:03',
            ),
            41 => 
            array (
                'autorizo' => '',
                'contrato_id' => 50,
                'created_at' => '2022-06-27 15:48:38',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 42,
                'reviso' => '',
                'updated_at' => '2022-06-27 15:48:38',
            ),
            42 => 
            array (
                'autorizo' => '',
                'contrato_id' => 51,
                'created_at' => '2022-06-27 16:10:32',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 43,
                'reviso' => '',
                'updated_at' => '2022-06-27 16:10:32',
            ),
            43 => 
            array (
                'autorizo' => '',
                'contrato_id' => 52,
                'created_at' => '2022-06-27 16:23:57',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 44,
                'reviso' => '',
                'updated_at' => '2022-06-27 16:23:57',
            ),
            44 => 
            array (
                'autorizo' => '',
                'contrato_id' => 53,
                'created_at' => '2022-07-11 16:17:08',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 45,
                'reviso' => '',
                'updated_at' => '2022-07-11 16:17:08',
            ),
            45 => 
            array (
                'autorizo' => '',
                'contrato_id' => 54,
                'created_at' => '2022-07-11 16:26:34',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 46,
                'reviso' => '',
                'updated_at' => '2022-07-11 16:26:34',
            ),
            46 => 
            array (
                'autorizo' => '',
                'contrato_id' => 55,
                'created_at' => '2022-07-11 16:37:53',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 47,
                'reviso' => '',
                'updated_at' => '2022-07-11 16:37:53',
            ),
            47 => 
            array (
                'autorizo' => '',
                'contrato_id' => 56,
                'created_at' => '2022-07-11 16:46:33',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 48,
                'reviso' => '',
                'updated_at' => '2022-07-11 16:46:33',
            ),
            48 => 
            array (
                'autorizo' => '',
                'contrato_id' => 57,
                'created_at' => '2022-07-11 17:06:42',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 49,
                'reviso' => '',
                'updated_at' => '2022-07-11 17:06:42',
            ),
            49 => 
            array (
                'autorizo' => '',
                'contrato_id' => 58,
                'created_at' => '2022-07-11 17:16:03',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 50,
                'reviso' => '',
                'updated_at' => '2022-07-11 17:16:03',
            ),
            50 => 
            array (
                'autorizo' => '',
                'contrato_id' => 59,
                'created_at' => '2022-07-12 08:35:42',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 51,
                'reviso' => '',
                'updated_at' => '2022-07-12 08:35:42',
            ),
            51 => 
            array (
                'autorizo' => '',
                'contrato_id' => 60,
                'created_at' => '2022-07-12 08:51:20',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 52,
                'reviso' => '',
                'updated_at' => '2022-07-12 08:51:20',
            ),
            52 => 
            array (
                'autorizo' => '',
                'contrato_id' => 61,
                'created_at' => '2022-07-12 09:07:32',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 53,
                'reviso' => '',
                'updated_at' => '2022-07-12 09:07:32',
            ),
            53 => 
            array (
                'autorizo' => '',
                'contrato_id' => 62,
                'created_at' => '2022-08-02 11:53:13',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 54,
                'reviso' => '',
                'updated_at' => '2022-08-02 11:53:13',
            ),
            54 => 
            array (
                'autorizo' => '',
                'contrato_id' => 63,
                'created_at' => '2022-08-09 12:22:53',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 55,
                'reviso' => '',
                'updated_at' => '2022-08-09 12:22:53',
            ),
            55 => 
            array (
                'autorizo' => '',
                'contrato_id' => 64,
                'created_at' => '2022-08-10 17:47:01',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 56,
                'reviso' => '',
                'updated_at' => '2022-08-10 17:47:01',
            ),
            56 => 
            array (
                'autorizo' => '',
                'contrato_id' => 65,
                'created_at' => '2022-08-15 12:35:42',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 57,
                'reviso' => '',
                'updated_at' => '2022-08-15 12:35:42',
            ),
            57 => 
            array (
                'autorizo' => '',
                'contrato_id' => 66,
                'created_at' => '2022-08-16 08:50:03',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 58,
                'reviso' => '',
                'updated_at' => '2022-08-16 08:50:03',
            ),
            58 => 
            array (
                'autorizo' => '',
                'contrato_id' => 67,
                'created_at' => '2022-09-02 15:02:52',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 59,
                'reviso' => '',
                'updated_at' => '2022-09-02 15:02:52',
            ),
            59 => 
            array (
                'autorizo' => '',
                'contrato_id' => 68,
                'created_at' => '2022-09-02 16:34:24',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 60,
                'reviso' => '',
                'updated_at' => '2022-09-02 16:34:24',
            ),
            60 => 
            array (
                'autorizo' => '',
                'contrato_id' => 69,
                'created_at' => '2022-09-02 17:41:34',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 61,
                'reviso' => '',
                'updated_at' => '2022-09-02 17:41:34',
            ),
            61 => 
            array (
                'autorizo' => '',
                'contrato_id' => 70,
                'created_at' => '2022-09-02 17:55:10',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 62,
                'reviso' => '',
                'updated_at' => '2022-09-02 17:55:10',
            ),
            62 => 
            array (
                'autorizo' => '',
                'contrato_id' => 71,
                'created_at' => '2022-09-02 18:45:02',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 63,
                'reviso' => '',
                'updated_at' => '2022-09-02 18:45:02',
            ),
            63 => 
            array (
                'autorizo' => '',
                'contrato_id' => 72,
                'created_at' => '2022-09-09 14:03:49',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 64,
                'reviso' => '',
                'updated_at' => '2022-09-09 14:03:49',
            ),
            64 => 
            array (
                'autorizo' => '',
                'contrato_id' => 73,
                'created_at' => '2022-09-09 14:18:03',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 65,
                'reviso' => '',
                'updated_at' => '2022-09-09 14:18:03',
            ),
            65 => 
            array (
                'autorizo' => '',
                'contrato_id' => 74,
                'created_at' => '2022-09-09 14:24:01',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 66,
                'reviso' => '',
                'updated_at' => '2022-09-09 14:24:01',
            ),
            66 => 
            array (
                'autorizo' => '',
                'contrato_id' => 75,
                'created_at' => '2022-09-23 09:08:36',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 67,
                'reviso' => '',
                'updated_at' => '2022-09-23 09:08:36',
            ),
            67 => 
            array (
                'autorizo' => '',
                'contrato_id' => 76,
                'created_at' => '2022-09-23 09:30:27',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 68,
                'reviso' => '',
                'updated_at' => '2022-09-23 09:30:27',
            ),
            68 => 
            array (
                'autorizo' => '',
                'contrato_id' => 77,
                'created_at' => '2022-09-23 14:51:16',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 69,
                'reviso' => '',
                'updated_at' => '2022-09-23 14:51:16',
            ),
            69 => 
            array (
                'autorizo' => '',
                'contrato_id' => 78,
                'created_at' => '2022-09-23 17:47:20',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 70,
                'reviso' => '',
                'updated_at' => '2022-09-23 17:47:20',
            ),
            70 => 
            array (
                'autorizo' => '',
                'contrato_id' => 79,
                'created_at' => '2022-09-27 11:21:23',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 71,
                'reviso' => '',
                'updated_at' => '2022-09-27 11:21:23',
            ),
            71 => 
            array (
                'autorizo' => '',
                'contrato_id' => 80,
                'created_at' => '2022-09-27 12:13:55',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 72,
                'reviso' => '',
                'updated_at' => '2022-09-27 12:13:55',
            ),
            72 => 
            array (
                'autorizo' => '',
                'contrato_id' => 81,
                'created_at' => '2022-09-27 13:07:46',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 73,
                'reviso' => '',
                'updated_at' => '2022-09-27 13:07:46',
            ),
            73 => 
            array (
                'autorizo' => '',
                'contrato_id' => 82,
                'created_at' => '2022-09-29 10:04:41',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 74,
                'reviso' => '',
                'updated_at' => '2022-09-29 10:04:41',
            ),
            74 => 
            array (
                'autorizo' => '',
                'contrato_id' => 83,
                'created_at' => '2022-09-29 13:29:27',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 75,
                'reviso' => '',
                'updated_at' => '2022-09-29 13:29:27',
            ),
            75 => 
            array (
                'autorizo' => '',
                'contrato_id' => 85,
                'created_at' => '2022-09-30 20:43:14',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 76,
                'reviso' => '',
                'updated_at' => '2022-09-30 20:43:14',
            ),
            76 => 
            array (
                'autorizo' => '',
                'contrato_id' => 84,
                'created_at' => '2022-09-30 20:43:15',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 77,
                'reviso' => '',
                'updated_at' => '2022-09-30 20:43:15',
            ),
            77 => 
            array (
                'autorizo' => '',
                'contrato_id' => 86,
                'created_at' => '2022-09-30 20:55:33',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 78,
                'reviso' => '',
                'updated_at' => '2022-09-30 20:55:33',
            ),
            78 => 
            array (
                'autorizo' => '',
                'contrato_id' => 87,
                'created_at' => '2022-09-30 20:59:40',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 79,
                'reviso' => '',
                'updated_at' => '2022-09-30 20:59:40',
            ),
            79 => 
            array (
                'autorizo' => '',
                'contrato_id' => 88,
                'created_at' => '2022-09-30 21:05:42',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 80,
                'reviso' => '',
                'updated_at' => '2022-09-30 21:05:42',
            ),
            80 => 
            array (
                'autorizo' => '',
                'contrato_id' => 89,
                'created_at' => '2022-10-03 19:55:09',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 81,
                'reviso' => '',
                'updated_at' => '2022-10-03 19:55:09',
            ),
            81 => 
            array (
                'autorizo' => '',
                'contrato_id' => 90,
                'created_at' => '2022-12-20 14:05:41',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 82,
                'reviso' => '',
                'updated_at' => '2022-12-20 14:05:41',
            ),
            82 => 
            array (
                'autorizo' => '',
                'contrato_id' => 91,
                'created_at' => '2022-12-20 15:19:26',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 83,
                'reviso' => '',
                'updated_at' => '2022-12-20 15:19:26',
            ),
            83 => 
            array (
                'autorizo' => '',
                'contrato_id' => 92,
                'created_at' => '2022-12-21 14:42:53',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 84,
                'reviso' => '',
                'updated_at' => '2022-12-21 14:42:53',
            ),
            84 => 
            array (
                'autorizo' => '',
                'contrato_id' => 93,
                'created_at' => '2022-12-22 11:03:11',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 85,
                'reviso' => '',
                'updated_at' => '2022-12-22 11:03:11',
            ),
            85 => 
            array (
                'autorizo' => '',
                'contrato_id' => 94,
                'created_at' => '2022-12-22 12:07:44',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 86,
                'reviso' => '',
                'updated_at' => '2022-12-22 12:07:44',
            ),
            86 => 
            array (
                'autorizo' => '',
                'contrato_id' => 95,
                'created_at' => '2022-12-22 12:43:41',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 87,
                'reviso' => '',
                'updated_at' => '2022-12-22 12:43:41',
            ),
            87 => 
            array (
                'autorizo' => '',
                'contrato_id' => 96,
                'created_at' => '2022-12-26 13:28:45',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 88,
                'reviso' => '',
                'updated_at' => '2022-12-26 13:28:45',
            ),
            88 => 
            array (
                'autorizo' => '',
                'contrato_id' => 97,
                'created_at' => '2022-12-26 13:54:54',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 89,
                'reviso' => '',
                'updated_at' => '2022-12-26 13:54:54',
            ),
            89 => 
            array (
                'autorizo' => '',
                'contrato_id' => 98,
                'created_at' => '2022-12-26 14:13:41',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 90,
                'reviso' => '',
                'updated_at' => '2022-12-26 14:13:41',
            ),
            90 => 
            array (
                'autorizo' => '',
                'contrato_id' => 99,
                'created_at' => '2022-12-26 14:54:10',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 91,
                'reviso' => '',
                'updated_at' => '2022-12-26 14:54:10',
            ),
            91 => 
            array (
                'autorizo' => '',
                'contrato_id' => 100,
                'created_at' => '2022-12-27 13:59:14',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 92,
                'reviso' => '',
                'updated_at' => '2022-12-27 13:59:14',
            ),
            92 => 
            array (
                'autorizo' => '',
                'contrato_id' => 101,
                'created_at' => '2022-12-27 14:18:52',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 93,
                'reviso' => '',
                'updated_at' => '2022-12-27 14:18:52',
            ),
            93 => 
            array (
                'autorizo' => '',
                'contrato_id' => 102,
                'created_at' => '2022-12-27 14:45:35',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 94,
                'reviso' => '',
                'updated_at' => '2022-12-27 14:45:35',
            ),
            94 => 
            array (
                'autorizo' => '',
                'contrato_id' => 103,
                'created_at' => '2022-12-29 12:34:30',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 95,
                'reviso' => '',
                'updated_at' => '2022-12-29 12:34:30',
            ),
            95 => 
            array (
                'autorizo' => '',
                'contrato_id' => 104,
                'created_at' => '2023-01-06 14:28:51',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 96,
                'reviso' => '',
                'updated_at' => '2023-01-06 14:28:51',
            ),
            96 => 
            array (
                'autorizo' => '',
                'contrato_id' => 105,
                'created_at' => '2023-01-06 14:48:59',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 97,
                'reviso' => '',
                'updated_at' => '2023-01-06 14:48:59',
            ),
            97 => 
            array (
                'autorizo' => '',
                'contrato_id' => 106,
                'created_at' => '2023-01-06 14:57:56',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 98,
                'reviso' => '',
                'updated_at' => '2023-01-06 14:57:56',
            ),
            98 => 
            array (
                'autorizo' => '',
                'contrato_id' => 107,
                'created_at' => '2023-01-10 10:51:50',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 99,
                'reviso' => '',
                'updated_at' => '2023-01-10 10:51:50',
            ),
            99 => 
            array (
                'autorizo' => '',
                'contrato_id' => 108,
                'created_at' => '2023-01-11 13:31:42',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 100,
                'reviso' => '',
                'updated_at' => '2023-01-11 13:31:42',
            ),
            100 => 
            array (
                'autorizo' => '',
                'contrato_id' => 109,
                'created_at' => '2023-01-11 15:25:41',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 101,
                'reviso' => '',
                'updated_at' => '2023-01-11 15:25:41',
            ),
            101 => 
            array (
                'autorizo' => '',
                'contrato_id' => 110,
                'created_at' => '2023-01-12 11:54:12',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 102,
                'reviso' => '',
                'updated_at' => '2023-01-12 11:54:12',
            ),
            102 => 
            array (
                'autorizo' => '',
                'contrato_id' => 111,
                'created_at' => '2023-01-12 12:15:54',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 103,
                'reviso' => '',
                'updated_at' => '2023-01-12 12:15:54',
            ),
            103 => 
            array (
                'autorizo' => '',
                'contrato_id' => 112,
                'created_at' => '2023-01-13 13:37:12',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 104,
                'reviso' => '',
                'updated_at' => '2023-01-13 13:37:12',
            ),
            104 => 
            array (
                'autorizo' => '',
                'contrato_id' => 113,
                'created_at' => '2023-01-13 13:52:48',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 105,
                'reviso' => '',
                'updated_at' => '2023-01-13 13:52:48',
            ),
            105 => 
            array (
                'autorizo' => '',
                'contrato_id' => 114,
                'created_at' => '2023-01-17 10:52:17',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 106,
                'reviso' => '',
                'updated_at' => '2023-01-17 10:52:17',
            ),
            106 => 
            array (
                'autorizo' => '',
                'contrato_id' => 115,
                'created_at' => '2023-01-17 14:35:22',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 107,
                'reviso' => '',
                'updated_at' => '2023-01-17 14:35:22',
            ),
            107 => 
            array (
                'autorizo' => '',
                'contrato_id' => 116,
                'created_at' => '2023-01-19 09:11:47',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 108,
                'reviso' => '',
                'updated_at' => '2023-01-19 09:11:47',
            ),
            108 => 
            array (
                'autorizo' => '',
                'contrato_id' => 117,
                'created_at' => '2023-01-19 14:23:47',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 109,
                'reviso' => '',
                'updated_at' => '2023-01-19 14:23:47',
            ),
            109 => 
            array (
                'autorizo' => '',
                'contrato_id' => 118,
                'created_at' => '2023-01-20 13:18:19',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 110,
                'reviso' => '',
                'updated_at' => '2023-01-20 13:18:19',
            ),
            110 => 
            array (
                'autorizo' => '',
                'contrato_id' => 119,
                'created_at' => '2023-01-24 12:20:38',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 111,
                'reviso' => '',
                'updated_at' => '2023-01-24 12:20:38',
            ),
            111 => 
            array (
                'autorizo' => '',
                'contrato_id' => 120,
                'created_at' => '2023-02-02 13:03:01',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 112,
                'reviso' => '',
                'updated_at' => '2023-02-02 13:03:01',
            ),
            112 => 
            array (
                'autorizo' => '',
                'contrato_id' => 121,
                'created_at' => '2023-02-02 13:54:51',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 113,
                'reviso' => '',
                'updated_at' => '2023-02-02 13:54:51',
            ),
            113 => 
            array (
                'autorizo' => '',
                'contrato_id' => 122,
                'created_at' => '2023-02-02 14:20:10',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 114,
                'reviso' => '',
                'updated_at' => '2023-02-02 14:20:10',
            ),
            114 => 
            array (
                'autorizo' => '',
                'contrato_id' => 123,
                'created_at' => '2023-02-02 14:31:53',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 115,
                'reviso' => '',
                'updated_at' => '2023-02-02 14:31:53',
            ),
            115 => 
            array (
                'autorizo' => '',
                'contrato_id' => 124,
                'created_at' => '2023-02-02 14:54:38',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 116,
                'reviso' => '',
                'updated_at' => '2023-02-02 14:54:38',
            ),
            116 => 
            array (
                'autorizo' => '',
                'contrato_id' => 125,
                'created_at' => '2023-02-09 12:07:05',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 117,
                'reviso' => '',
                'updated_at' => '2023-02-09 12:07:05',
            ),
            117 => 
            array (
                'autorizo' => '',
                'contrato_id' => 126,
                'created_at' => '2023-02-09 12:55:01',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 118,
                'reviso' => '',
                'updated_at' => '2023-02-09 12:55:01',
            ),
            118 => 
            array (
                'autorizo' => '',
                'contrato_id' => 127,
                'created_at' => '2023-02-09 13:38:49',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 119,
                'reviso' => '',
                'updated_at' => '2023-02-09 13:38:49',
            ),
            119 => 
            array (
                'autorizo' => '',
                'contrato_id' => 128,
                'created_at' => '2023-02-13 11:37:19',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 120,
                'reviso' => '',
                'updated_at' => '2023-02-13 11:37:19',
            ),
            120 => 
            array (
                'autorizo' => '',
                'contrato_id' => 129,
                'created_at' => '2023-02-13 12:51:29',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 121,
                'reviso' => '',
                'updated_at' => '2023-02-13 12:51:29',
            ),
            121 => 
            array (
                'autorizo' => '',
                'contrato_id' => 130,
                'created_at' => '2023-02-13 13:26:25',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 122,
                'reviso' => '',
                'updated_at' => '2023-02-13 13:26:25',
            ),
            122 => 
            array (
                'autorizo' => '',
                'contrato_id' => 131,
                'created_at' => '2023-02-13 13:50:14',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 123,
                'reviso' => '',
                'updated_at' => '2023-02-13 13:50:14',
            ),
            123 => 
            array (
                'autorizo' => '',
                'contrato_id' => 132,
                'created_at' => '2023-02-13 15:51:30',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 124,
                'reviso' => '',
                'updated_at' => '2023-02-13 15:51:30',
            ),
            124 => 
            array (
                'autorizo' => '',
                'contrato_id' => 133,
                'created_at' => '2023-02-13 16:49:18',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 125,
                'reviso' => '',
                'updated_at' => '2023-02-13 16:49:18',
            ),
            125 => 
            array (
                'autorizo' => '',
                'contrato_id' => 134,
                'created_at' => '2023-02-14 12:51:38',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 126,
                'reviso' => '',
                'updated_at' => '2023-02-14 12:51:38',
            ),
            126 => 
            array (
                'autorizo' => '',
                'contrato_id' => 135,
                'created_at' => '2023-02-14 13:08:27',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 127,
                'reviso' => '',
                'updated_at' => '2023-02-14 13:08:27',
            ),
            127 => 
            array (
                'autorizo' => '',
                'contrato_id' => 136,
                'created_at' => '2023-02-14 13:33:02',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 128,
                'reviso' => '',
                'updated_at' => '2023-02-14 13:33:02',
            ),
            128 => 
            array (
                'autorizo' => '',
                'contrato_id' => 137,
                'created_at' => '2023-02-14 13:55:34',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 129,
                'reviso' => '',
                'updated_at' => '2023-02-14 13:55:34',
            ),
            129 => 
            array (
                'autorizo' => '',
                'contrato_id' => 138,
                'created_at' => '2023-02-14 17:09:46',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 130,
                'reviso' => '',
                'updated_at' => '2023-02-14 17:09:46',
            ),
            130 => 
            array (
                'autorizo' => '',
                'contrato_id' => 139,
                'created_at' => '2023-02-15 10:21:59',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 131,
                'reviso' => '',
                'updated_at' => '2023-02-15 10:21:59',
            ),
            131 => 
            array (
                'autorizo' => '',
                'contrato_id' => 140,
                'created_at' => '2023-02-23 11:20:19',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 132,
                'reviso' => '',
                'updated_at' => '2023-02-23 11:20:19',
            ),
            132 => 
            array (
                'autorizo' => '',
                'contrato_id' => 141,
                'created_at' => '2023-02-23 12:01:06',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 133,
                'reviso' => '',
                'updated_at' => '2023-02-23 12:01:06',
            ),
            133 => 
            array (
                'autorizo' => '',
                'contrato_id' => 142,
                'created_at' => '2023-03-03 10:00:36',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 134,
                'reviso' => '',
                'updated_at' => '2023-03-03 10:00:36',
            ),
            134 => 
            array (
                'autorizo' => '',
                'contrato_id' => 143,
                'created_at' => '2023-03-07 11:46:56',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 135,
                'reviso' => '',
                'updated_at' => '2023-03-07 11:46:56',
            ),
            135 => 
            array (
                'autorizo' => '',
                'contrato_id' => 144,
                'created_at' => '2023-03-07 13:05:23',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 136,
                'reviso' => '',
                'updated_at' => '2023-03-07 13:05:23',
            ),
            136 => 
            array (
                'autorizo' => '',
                'contrato_id' => 145,
                'created_at' => '2023-03-07 13:42:06',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 137,
                'reviso' => '',
                'updated_at' => '2023-03-07 13:42:06',
            ),
            137 => 
            array (
                'autorizo' => '',
                'contrato_id' => 146,
                'created_at' => '2023-03-07 13:57:46',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 138,
                'reviso' => '',
                'updated_at' => '2023-03-07 13:57:46',
            ),
            138 => 
            array (
                'autorizo' => '',
                'contrato_id' => 147,
                'created_at' => '2023-03-08 10:34:08',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 139,
                'reviso' => '',
                'updated_at' => '2023-03-08 10:34:08',
            ),
            139 => 
            array (
                'autorizo' => '',
                'contrato_id' => 148,
                'created_at' => '2023-03-15 13:10:51',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 140,
                'reviso' => '',
                'updated_at' => '2023-03-15 13:10:51',
            ),
            140 => 
            array (
                'autorizo' => '',
                'contrato_id' => 149,
                'created_at' => '2023-03-15 15:28:34',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 141,
                'reviso' => '',
                'updated_at' => '2023-03-15 15:28:34',
            ),
            141 => 
            array (
                'autorizo' => '',
                'contrato_id' => 150,
                'created_at' => '2023-03-15 15:58:51',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 142,
                'reviso' => '',
                'updated_at' => '2023-03-15 15:58:51',
            ),
            142 => 
            array (
                'autorizo' => '',
                'contrato_id' => 151,
                'created_at' => '2023-04-06 11:20:16',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 143,
                'reviso' => '',
                'updated_at' => '2023-04-06 11:20:16',
            ),
            143 => 
            array (
                'autorizo' => '',
                'contrato_id' => 152,
                'created_at' => '2023-04-10 14:09:20',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 144,
                'reviso' => '',
                'updated_at' => '2023-04-10 14:09:20',
            ),
            144 => 
            array (
                'autorizo' => '',
                'contrato_id' => 153,
                'created_at' => '2023-04-10 14:24:24',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 145,
                'reviso' => '',
                'updated_at' => '2023-04-10 14:24:24',
            ),
            145 => 
            array (
                'autorizo' => '',
                'contrato_id' => 154,
                'created_at' => '2023-04-10 15:19:04',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 146,
                'reviso' => '',
                'updated_at' => '2023-04-10 15:19:04',
            ),
            146 => 
            array (
                'autorizo' => '',
                'contrato_id' => 155,
                'created_at' => '2023-04-11 09:54:01',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 147,
                'reviso' => '',
                'updated_at' => '2023-04-11 09:54:01',
            ),
            147 => 
            array (
                'autorizo' => '',
                'contrato_id' => 156,
                'created_at' => '2023-04-11 10:17:57',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 148,
                'reviso' => '',
                'updated_at' => '2023-04-11 10:17:57',
            ),
            148 => 
            array (
                'autorizo' => '',
                'contrato_id' => 157,
                'created_at' => '2023-04-12 14:54:44',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 149,
                'reviso' => '',
                'updated_at' => '2023-04-12 14:54:44',
            ),
            149 => 
            array (
                'autorizo' => '',
                'contrato_id' => 158,
                'created_at' => '2023-04-13 10:01:59',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 150,
                'reviso' => '',
                'updated_at' => '2023-04-13 10:01:59',
            ),
            150 => 
            array (
                'autorizo' => '',
                'contrato_id' => 159,
                'created_at' => '2023-04-14 21:07:58',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 151,
                'reviso' => '',
                'updated_at' => '2023-04-14 21:07:58',
            ),
            151 => 
            array (
                'autorizo' => '',
                'contrato_id' => 160,
                'created_at' => '2023-04-19 14:48:47',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 152,
                'reviso' => '',
                'updated_at' => '2023-04-19 14:48:47',
            ),
            152 => 
            array (
                'autorizo' => '',
                'contrato_id' => 161,
                'created_at' => '2023-04-24 09:40:32',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 153,
                'reviso' => '',
                'updated_at' => '2023-04-24 09:40:32',
            ),
            153 => 
            array (
                'autorizo' => '',
                'contrato_id' => 162,
                'created_at' => '2023-04-27 14:03:47',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 154,
                'reviso' => '',
                'updated_at' => '2023-04-27 14:03:47',
            ),
            154 => 
            array (
                'autorizo' => '',
                'contrato_id' => 163,
                'created_at' => '2023-06-14 09:54:10',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 155,
                'reviso' => '',
                'updated_at' => '2023-06-14 09:54:10',
            ),
            155 => 
            array (
                'autorizo' => '',
                'contrato_id' => 164,
                'created_at' => '2023-06-14 10:38:52',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 156,
                'reviso' => '',
                'updated_at' => '2023-06-14 10:38:52',
            ),
            156 => 
            array (
                'autorizo' => '',
                'contrato_id' => 165,
                'created_at' => '2023-08-14 16:30:54',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 157,
                'reviso' => '',
                'updated_at' => '2023-08-14 16:30:54',
            ),
            157 => 
            array (
                'autorizo' => '',
                'contrato_id' => 166,
                'created_at' => '2023-08-16 14:05:13',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 158,
                'reviso' => '',
                'updated_at' => '2023-08-16 14:05:13',
            ),
            158 => 
            array (
                'autorizo' => '',
                'contrato_id' => 167,
                'created_at' => '2023-08-16 18:12:36',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 159,
                'reviso' => '',
                'updated_at' => '2023-08-16 18:12:36',
            ),
            159 => 
            array (
                'autorizo' => '',
                'contrato_id' => 168,
                'created_at' => '2023-08-21 14:36:27',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 160,
                'reviso' => '',
                'updated_at' => '2023-08-21 14:36:27',
            ),
            160 => 
            array (
                'autorizo' => '',
                'contrato_id' => 169,
                'created_at' => '2023-08-21 14:38:41',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 161,
                'reviso' => '',
                'updated_at' => '2023-08-21 14:38:41',
            ),
            161 => 
            array (
                'autorizo' => '',
                'contrato_id' => 170,
                'created_at' => '2023-08-22 16:37:17',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 162,
                'reviso' => '',
                'updated_at' => '2023-08-22 16:37:17',
            ),
            162 => 
            array (
                'autorizo' => '',
                'contrato_id' => 171,
                'created_at' => '2023-08-24 13:29:20',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 163,
                'reviso' => '',
                'updated_at' => '2023-08-24 13:29:20',
            ),
            163 => 
            array (
                'autorizo' => '',
                'contrato_id' => 172,
                'created_at' => '2023-09-04 10:52:54',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 164,
                'reviso' => '',
                'updated_at' => '2023-09-04 10:52:54',
            ),
            164 => 
            array (
                'autorizo' => '',
                'contrato_id' => 173,
                'created_at' => '2023-09-04 11:01:00',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 165,
                'reviso' => '',
                'updated_at' => '2023-09-04 11:01:00',
            ),
            165 => 
            array (
                'autorizo' => '',
                'contrato_id' => 174,
                'created_at' => '2023-09-04 11:50:54',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 166,
                'reviso' => '',
                'updated_at' => '2023-09-04 11:50:54',
            ),
            166 => 
            array (
                'autorizo' => '',
                'contrato_id' => 175,
                'created_at' => '2023-09-04 12:17:14',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 167,
                'reviso' => '',
                'updated_at' => '2023-09-04 12:17:14',
            ),
            167 => 
            array (
                'autorizo' => '',
                'contrato_id' => 176,
                'created_at' => '2023-09-04 12:35:12',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 168,
                'reviso' => '',
                'updated_at' => '2023-09-04 12:35:12',
            ),
            168 => 
            array (
                'autorizo' => '',
                'contrato_id' => 177,
                'created_at' => '2023-09-04 12:47:36',
                'cumple' => '1',
                'deleted_at' => NULL,
                'elaboro' => '',
                'id' => 169,
                'reviso' => '',
                'updated_at' => '2023-09-04 12:47:36',
            ),
        ));
        
        
    }
}