<?php

namespace Database\Seeders;

use App\Models\GapDo;
use Illuminate\Database\Seeder;

class GapdosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $gapdo = [
            [
                'control-uno' => "A5",
                'control-dos' => "A5.1",
                'anexo_indice' => "A5.1.1",
                'anexo_politica' => "Políticas para la seguridad de la información",
            ],
            [
                'control-uno' => "A5",
                'control-dos' => "A5.1",
                'anexo_indice' => "A5.1.2",
                'anexo_politica' => "Revisión de las políticas para la seguridad de la información.",
            ],
            [
                'control-uno' => "A6",
                'control-dos' => "A6.1",
                'anexo_indice' => "A6.1.1",
                'anexo_politica' => "Roles y responsabilidades para la seguridad de la información",
            ],
            [
                'control-uno' => "A6",
                'control-dos' => "A6.1",
                'anexo_indice' => "A6.1.2",
                'anexo_politica' => "Separación de deberes",
            ],
            [
                'control-uno' => "A6",
                'control-dos' => "A6.1",
                'anexo_indice' => "A6.1.3",
                'anexo_politica' => "Contacto con las autoridades",
            ],
            [
                'control-uno' => "A6",
                'control-dos' => "A6.1",
                'anexo_indice' => "A6.1.4",
                'anexo_politica' => "Contacto con grupos de interés especial",
            ],
            [
                'control-uno' => "A6",
                'control-dos' => "A6.1",
                'anexo_indice' => "A6.1.5",
                'anexo_politica' => "Seguridad de la información en la gestión de proyectos.",
            ],
            [
                'control-uno' => "A6",
                'control-dos' => "A6.2",
                'anexo_indice' => "A6.2.1",
                'anexo_politica' => "Política para dispositivos móviles",
            ],
            [
                'control-uno' => "A6",
                'control-dos' => "A6.2",
                'anexo_indice' => "A6.2.2",
                'anexo_politica' => "Teletrabajo",
            ],
            [
                'control-uno' => "A7",
                'control-dos' => "A7.1",
                'anexo_indice' => "A7.1.1",
                'anexo_politica' => "Selección",
            ],
            [
                'control-uno' => "A7",
                'control-dos' => "A7.1",
                'anexo_indice' => "A7.1.2",
                'anexo_politica' => "Términos y condiciones del empleo",
            ],
            [
                'control-uno' => "A7",
                'control-dos' => "A7.2",
                'anexo_indice' => "A7.2.2",
                'anexo_politica' => "Toma de conciencia, educación y formación en la seguridad de la información.",
            ],
            [
                'control-uno' => "A7",
                'control-dos' => "A7.2",
                'anexo_indice' => "A7.2.3",
                'anexo_politica' => "Proceso disciplinario",
            ],
            [
                'control-uno' => "A7",
                'control-dos' => "A7.3",
                'anexo_indice' => "A7.3.1",
                'anexo_politica' => "Terminación o cambio de responsabilidades de empleo",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.1",
                'anexo_indice' => "A8.1.1",
                'anexo_politica' => "Inventario de activos",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.1",
                'anexo_indice' => "A8.1.2",
                'anexo_politica' => "Propiedad de los activos",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.1",
                'anexo_indice' => "A8.1.3",
                'anexo_politica' => "Uso aceptable de los activos",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.1",
                'anexo_indice' => "A8.1.4",
                'anexo_politica' => "Devolución de activos",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.2",
                'anexo_indice' => "A8.2.1",
                'anexo_politica' => "Clasificación de la información",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.2",
                'anexo_indice' => "A8.2.2",
                'anexo_politica' => "Etiquetado de la información",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.2",
                'anexo_indice' => "A8.2.3",
                'anexo_politica' => "Manejo de activos",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.3",
                'anexo_indice' => "A8.3.1",
                'anexo_politica' => "Gestión de medios removibles",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.3",
                'anexo_indice' => "A8.3.2",
                'anexo_politica' => "Disposición de los medios",
            ],
            [
                'control-uno' => "A8",
                'control-dos' => "A8.3",
                'anexo_indice' => "A8.3.3",
                'anexo_politica' => "Transferencia de medios físicos",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.1",
                'anexo_indice' => "A9.1.1",
                'anexo_politica' => "Política de control de acceso",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.1",
                'anexo_indice' => "A9.1.2",
                'anexo_politica' => "Acceso a redes y a servicios en red",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.2",
                'anexo_indice' => "A9.2.1",
                'anexo_politica' => "Registro y cancelación del registro de usuarios",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.2",
                'anexo_indice' => "A9.2.2",
                'anexo_politica' => "Suministro de acceso de usuarios",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.2",
                'anexo_indice' => "A9.2.3",
                'anexo_politica' => "Gestión de derechos de acceso privilegiado",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.2",
                'anexo_indice' => "A9.2.4",
                'anexo_politica' => "Gestión de información de autenticación secreta de usuarios",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.2",
                'anexo_indice' => "A9.2.5",
                'anexo_politica' => "Revisión de los derechos de acceso de usuarios",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.2",
                'anexo_indice' => "A9.2.6",
                'anexo_politica' => "Retiro o ajuste de los derechos de acceso",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.3",
                'anexo_indice' => "A9.3.1",
                'anexo_politica' => "Uso de información de autenticación secreta",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.4",
                'anexo_indice' => "A9.4.1",
                'anexo_politica' => "Restricción de acceso a la información",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.4",
                'anexo_indice' => "A9.4.2",
                'anexo_politica' => "Procedimiento de ingreso seguro",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.4",
                'anexo_indice' => "A9.4.3",
                'anexo_politica' => "Sistema de gestión de contraseñas",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.4",
                'anexo_indice' => "A9.4.4",
                'anexo_politica' => "Uso de programas utilitarios privilegiados",
            ],
            [
                'control-uno' => "A9",
                'control-dos' => "A9.4",
                'anexo_indice' => "A9.4.5",
                'anexo_politica' => "Control de acceso a códigos fuente de programas",
            ],
            [
                'control-uno' => "A10",
                'control-dos' => "A10.1",
                'anexo_indice' => "A10.1.1",
                'anexo_politica' => "Política sobre el uso de controles criptográficos",
            ],
            [
                'control-uno' => "A10",
                'control-dos' => "A10.1",
                'anexo_indice' => "A10.1.2",
                'anexo_politica' => "Gestión de llaves",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.1",
                'anexo_indice' => "A11.1.1",
                'anexo_politica' => "Perímetro de seguridad física",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.1",
                'anexo_indice' => "A11.1.2",
                'anexo_politica' => "Controles de acceso físicos",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.1",
                'anexo_indice' => "A11.1.3",
                'anexo_politica' => "Seguridad de oficinas, recintos e instalaciones",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.1",
                'anexo_indice' => "A11.1.4",
                'anexo_politica' => "Protección contra amenazas externas y ambientales.",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.1",
                'anexo_indice' => "A11.1.5",
                'anexo_politica' => "Trabajo en áreas seguras.",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.1",
                'anexo_indice' => "A11.1.6",
                'anexo_politica' => "Áreas de carga, despacho y acceso público",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.1",
                'anexo_politica' => "Ubicación y protección de los equipos",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.2",
                'anexo_politica' => "Servicios de suministro",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.3",
                'anexo_politica' => "Seguridad en el cableado.",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.4",
                'anexo_politica' => "Mantenimiento de los equipos.",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.5",
                'anexo_politica' => "Retiro de activos",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.6",
                'anexo_politica' => "Seguridad de equipos y activos fuera de las instalaciones",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.7",
                'anexo_politica' => "Disposición segura o reutilización de equipos",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.8",
                'anexo_politica' => "Equipos de usuario desatendido",
            ],
            [
                'control-uno' => "A11",
                'control-dos' => "A11.2",
                'anexo_indice' => "A11.2.9",
                'anexo_politica' => "Política de escritorio limpio y pantalla limpia",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.1",
                'anexo_indice' => "A12.1.1",
                'anexo_politica' => "Procedimientos de operación documentados",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.1",
                'anexo_indice' => "A12.1.2",
                'anexo_politica' => "Gestión de cambios",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.1",
                'anexo_indice' => "A12.1.3",
                'anexo_politica' => "Gestión de capacidad",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.1",
                'anexo_indice' => "A12.1.4",
                'anexo_politica' => "Separación de los ambientes de desarrollo, pruebas y operación",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.2",
                'anexo_indice' => "A12.2.1",
                'anexo_politica' => "Controles contra códigos maliciosos",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.3",
                'anexo_indice' => "A12.3.1",
                'anexo_politica' => "Respaldo de la información",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.4",
                'anexo_indice' => "A12.4.1",
                'anexo_politica' => "Registro de eventos",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.4",
                'anexo_indice' => "A12.4.2",
                'anexo_politica' => "Protección de la información de registro",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.4",
                'anexo_indice' => "A12.4.3",
                'anexo_politica' => "Registros del administrador y del operador",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.4",
                'anexo_indice' => "A12.4.4",
                'anexo_politica' => "Sincronización de relojes",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.5",
                'anexo_indice' => "A12.5.1",
                'anexo_politica' => "Instalación de software en sistemas operativos",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.6",
                'anexo_indice' => "A12.6.1",
                'anexo_politica' => "Gestión de las vulnerabilidades técnicas",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.6",
                'anexo_indice' => "A12.6.2",
                'anexo_politica' => "Restricciones sobre la instalación de software",
            ],
            [
                'control-uno' => "A12",
                'control-dos' => "A12.7",
                'anexo_indice' => "A12.7.1",
                'anexo_politica' => "Controles de auditorías de sistemas de información",
            ],
            [
                'control-uno' => "A13",
                'control-dos' => "A13.1",
                'anexo_indice' => "A13.1.1",
                'anexo_politica' => "Controles de redes",
            ],
            [
                'control-uno' => "A13",
                'control-dos' => "A13.1",
                'anexo_indice' => "A13.1.2",
                'anexo_politica' => "Seguridad  de los servicios de red",
            ],
            [
                'control-uno' => "A13",
                'control-dos' => "A13.1",
                'anexo_indice' => "A13.1.3",
                'anexo_politica' => "Seguridad  de los servicios de red",
            ],
            [
                'control-uno' => "A13",
                'control-dos' => "A13.2",
                'anexo_indice' => "A13.2.1",
                'anexo_politica' => "Políticas y procedimientos de transferencia de información",
            ],
            [
                'control-uno' => "A13",
                'control-dos' => "A13.2",
                'anexo_indice' => "A13.2.2",
                'anexo_politica' => "Acuerdos sobre transferencia de información",
            ],
            [
                'control-uno' => "A13",
                'control-dos' => "A13.2",
                'anexo_indice' => "A13.2.3",
                'anexo_politica' => "Mensajería Electronica",
            ],
            [
                'control-uno' => "A13",
                'control-dos' => "A13.2",
                'anexo_indice' => "A13.2.4",
                'anexo_politica' => "Acuerdos de confidencialidad o de no divulgación",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.1",
                'anexo_indice' => "A14.1.1",
                'anexo_politica' => "Análisis y especificación de requisitos de seguridad de la información",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.1",
                'anexo_indice' => "A14.1.2",
                'anexo_politica' => "Seguridad de servicios de las aplicaciones en redes públicas",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.1",
                'anexo_indice' => "A14.1.3",
                'anexo_politica' => "Protección de transaccciones de los servicios de las aplicaciones.",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.1",
                'anexo_politica' => "Política de desarrollo seguro",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.2",
                'anexo_politica' => "Procedimientos de control de cambios en sistemas",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.3",
                'anexo_politica' => "Revisión técnica de las aplicaciones después de cambios en la plataforma de operación",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.4",
                'anexo_politica' => "Restricciones en los cambios a los paquetes de software",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.5",
                'anexo_politica' => "Principio de Construcción de los Sistemas Seguros.",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.6",
                'anexo_politica' => "Ambiente de desarrollo seguro",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.7",
                'anexo_politica' => "Desarrollo contratado externamente",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.8",
                'anexo_politica' => "Pruebas de seguridad de sistemas",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.2",
                'anexo_indice' => "A14.2.9",
                'anexo_politica' => "Prueba de aceptación de sistemas",
            ],
            [
                'control-uno' => "A14",
                'control-dos' => "A14.3",
                'anexo_indice' => "A14.3.1",
                'anexo_politica' => "Protección de datos de prueba",
            ],
            [
                'control-uno' => "A15",
                'control-dos' => "A15.1",
                'anexo_indice' => "A15.1.1",
                'anexo_politica' => "Política de seguridad de la información para las relaciones con proveedores",
            ],
            [
                'control-uno' => "A15",
                'control-dos' => "A15.1",
                'anexo_indice' => "A15.1.2",
                'anexo_politica' => "Tratamiento de la seguridad dentro de los acuerdos con proveedores",
            ],
            [
                'control-uno' => "A15",
                'control-dos' => "A15.1",
                'anexo_indice' => "A15.1.3",
                'anexo_politica' => "Cadena de suministro de tecnología de información y comunicación",
            ],
            [
                'control-uno' => "A15",
                'control-dos' => "A15.2",
                'anexo_indice' => "A15.2.1",
                'anexo_politica' => "Seguimiento y revisión de los servicios de los proveedores",
            ],
            [
                'control-uno' => "A15",
                'control-dos' => "A15.2",
                'anexo_indice' => "A15.2.2",
                'anexo_politica' => "Gestión del cambio en los servicios de los proveedores",
            ],
            [
                'control-uno' => "A16",
                'control-dos' => "A16.1",
                'anexo_indice' => "A16.1.1",
                'anexo_politica' => "Responsabilidades y procedimientos",
            ],
            [
                'control-uno' => "A16",
                'control-dos' => "A16.1",
                'anexo_indice' => "A16.1.2",
                'anexo_politica' => "Reporte de eventos de seguridad de la información",
            ],
            [
                'control-uno' => "A16",
                'control-dos' => "A16.1",
                'anexo_indice' => "A16.1.3",
                'anexo_politica' => "Reporte de debilidades de seguridad de la información",
            ],
            [
                'control-uno' => "A16",
                'control-dos' => "A16.1",
                'anexo_indice' => "A16.1.4",
                'anexo_politica' => "Evaluación de eventos de seguridad de la información y decisiones sobre ellos",
            ],
            [
                'control-uno' => "A16",
                'control-dos' => "A16.1",
                'anexo_indice' => "A16.1.5",
                'anexo_politica' => "Respuesta a incidentes de seguridad de la información",
            ],
            [
                'control-uno' => "A16",
                'control-dos' => "A16.1",
                'anexo_indice' => "A16.1.6",
                'anexo_politica' => "Aprendizaje obtenido de los incidentes de seguridad de la información",
            ],
            [
                'control-uno' => "A16",
                'control-dos' => "A16.1",
                'anexo_indice' => "A16.1.7",
                'anexo_politica' => "Recolección de evidencia",
            ],
            [
                'control-uno' => "A17",
                'control-dos' => "A17.1",
                'anexo_indice' => "A17.1.1",
                'anexo_politica' => "Planificación de la continuidad de la seguridad de la información ",
            ],
            [
                'control-uno' => "A17",
                'control-dos' => "A17.1",
                'anexo_indice' => "A17.1.2",
                'anexo_politica' => "Implementación de la continuidad de la seguridad de la información ",
            ],
            [
                'control-uno' => "A17",
                'control-dos' => "A17.1",
                'anexo_indice' => "A17.1.3",
                'anexo_politica' => "Verificación, revisión y evaluación de la continuidad de la seguridad de la información ",
            ],
            [
                'control-uno' => "A17",
                'control-dos' => "A17.2",
                'anexo_indice' => "A17.2.1",
                'anexo_politica' => "Disponibilidad de instalaciones de procesamiento de información",
            ],
            [
                'control-uno' => "A18",
                'control-dos' => "A18.1",
                'anexo_indice' => "A18.1.1",
                'anexo_politica' => "Identificación de la legislación aplicable.",
            ],
            [
                'control-uno' => "A18",
                'control-dos' => "A18.1",
                'anexo_indice' => "A18.1.2",
                'anexo_politica' => "Derechos propiedad intelectual (DPI)",
            ],
            [
                'control-uno' => "A18",
                'control-dos' => "A18.1",
                'anexo_indice' => "A18.1.3",
                'anexo_politica' => "Protección de registros",
            ],
            [
                'control-uno' => "A18",
                'control-dos' => "A18.1",
                'anexo_indice' => "A18.1.4",
                'anexo_politica' => "Privacidad y protección de información de datos personales",
            ],
            [
                'control-uno' => "A18",
                'control-dos' => "A18.1",
                'anexo_indice' => "A18.1.5",
                'anexo_politica' => "Reglamentación de controles criptográficos.",
            ],
            [
                'control-uno' => "A18",
                'control-dos' => "A18.2",
                'anexo_indice' => "A18.2.1",
                'anexo_politica' => "Revisión independiente de la seguridad de la información ",
            ],
            [
                'control-uno' => "A18",
                'control-dos' => "A18.2",
                'anexo_indice' => "A18.2.2",
                'anexo_politica' => "Cumplimiento con las políticas y normas de seguridad",
            ],
            [
                'control-uno' => "A18",
                'control-dos' => "A18.2",
                'anexo_indice' => "A18.2.3",
                'anexo_politica' => "Revisión del cumplimiento técnico",
            ],
        ];

        GapDo::insert($gapdo);
    }
}
