<?php

namespace Database\Seeders;

use App\Models\PlanImplementacion;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class PlanImplementacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $planbs = [
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '1',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'PLAN DE TRABAJO BASE',
                'level' => '0',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '2',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'ANALISIS INICIAL',
                'level' => '1',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '3',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Realizar levantamiento de información con formulario de estado actual',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '4',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Evaluar tablero y presentar resultados a dirección',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '5',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Identificar brechas y esfuerzos',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '6',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'PLANEACIÓN',
                'level' => '1',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '7',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Identificar el Contexto de la Organización',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '8',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Entendimiento de las necesidades y expectativas de las partes interesadas',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '9',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Manual del SGI',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '10',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Elaborar matriz FODA',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '11',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Determinar Alcance del SGSI',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '12',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Política de Seguridad de Información',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '13',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Objetivos del SGSI',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '14',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Análisis y Evaluación de Riesgos',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '15',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Inventario de activos de Información',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '16',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Evaluación y valoración del Riesgo',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '17',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Plan de Tratamiento de Riesgos conforme a los controles de seguridad',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '18',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Declaración de aplicabilidad SoA',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '19',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'SOPORTE',
                'level' => '1',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '20',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Compromiso de la Alta Dirección',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '21',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Asignación de Recursos',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '22',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Conformar el Comité de Seguridad',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '23',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Elaborar matriz de roles y responsabilidades',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '24',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Competencias y capacitación',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '25',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Descripciones de puesto',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '26',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Control de capacitación del personal',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '27',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Comunicación del SGSI',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '28',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'OPERACIÓN DE SGSI',
                'level' => '1',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '29',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Procesos de gestión',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '30',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Información documentada',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '31',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Acciones correctivas',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '32',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Auditoria interna',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '33',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Gestión de incidentes de seguridad de la información',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '34',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Manual de Políticas de seguridad de la información',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '35',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.5 Políticas de seguridad de información',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '36',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.6 Organización de la seguridad de información',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '37',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.7 Seguridad en recursos humanos',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '38',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.8 Administración de activos',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '39',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.9 Control de acceso',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '40',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.10 Criptografía',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '41',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.11 Seguridad física y ambiental',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '42',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.12 Seguridad en operaciones',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '43',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.13 Seguridad en comunicaciones',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '44',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.14 Adquisición, desarrollo y mantenimiento de sistemas',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '45',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.15 Relación con proveedores',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '46',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.16 Administración de incidentes de seguridad de la información',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '47',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.17 Aspectos de seguridad de la información en la administración de continuidad del negocio',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '48',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'A.18 Cumplimiento',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '49',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'EVALUACIÓN',
                'level' => '1',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '50',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Auditoría Interna',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '51',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Evaluación',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '52',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Reporte de Auditoría',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '53',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Consolidación de Información para la Revisión de la Dirección',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '54',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Revisión de la Dirección',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '55',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Revisión de resultados de auditoría y desempeño del SGSI',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '56',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'MEJORA CONTINUA',
                'level' => '1',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '57',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Documentación de Acciones Correctivas y mejora',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '58',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Cierre de acciones de mejora',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '59',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Cierre de acciones correctivas de la Auditoria Interna y/o externa',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],
            [
                'id' => 'tmp' . Carbon::now()->timestamp . '60',
                'end' => Carbon::now()->timestamp * 1000,
                'name' => 'Cierre de acciones correctivas derivadas de la Revisión de la Dirección',
                'level' => '2',
                'start' => Carbon::now()->timestamp * 1000,
                'canAdd' => true,
                'status' => 'STATUS_UNDEFINED',
                'canWrite' => true,
                'duration' => '1',
                'progress' => '0',
                'canDelete' => true,
                'collapsed' => false,
                'relevance' => '0',
                'canAddIssue' => true,
                'endIsMilestone' => false,
                'startIsMilestone' => false,
                'progressByWorklog' => false,
            ],

        ];

        PlanImplementacion::create([ // Necesario se carga inicialmente el Diagrama Universal de Gantt
            'tasks' => $planbs,
            'canAdd' => true,
            'canWrite' => true,
            'canWriteOnParent' => true,
            'changesReasonWhy' => false,
            'selectedRow' => 0,
            'zoom' => '3d',
            'parent' => 'Plan de Implementación',
            'norma' => 'ISO 27001',
            'modulo_origen' => 'Implementación',
            'objetivo' => 'Implementar un Sistema de Gestión de Seguridad de la Información basado en el ciclo Deming que cumpla con todos los requisitos pautados en la norma ISO 27001.',
            'elaboro_id' => null,
        ]);
    }
}
