<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductosTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('productos')->delete();

        \DB::table('productos')->insert([
            0 => [
                'id' => 1,
                'descripcion' => 'Servicio de administración telefónica',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '1',
            ],
            1 => [
                'id' => 2,
                'descripcion' => 'Educación y Capacitación',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '2',
            ],
            2 => [
                'id' => 3,
                'descripcion' => 'Gestión de eventos',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '3',
            ],
            3 => [
                'id' => 4,
                'descripcion' => 'Papeleria',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '4',
            ],
            4 => [
                'id' => 5,
                'descripcion' => 'Servicio de mensajeria y transporte',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '5',
            ],
            5 => [
                'id' => 6,
                'descripcion' => 'Servicios de mantenimiento',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '6',
            ],
            6 => [
                'id' => 7,
                'descripcion' => 'Membresías',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '7',
            ],
            7 => [
                'id' => 8,
                'descripcion' => 'Ferias de empleo',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '8',
            ],
            8 => [
                'id' => 9,
                'descripcion' => 'Reclutamiento',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '9',
            ],
            9 => [
                'id' => 10,
                'descripcion' => 'Licencias Software',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '10',
            ],
            10 => [
                'id' => 11,
                'descripcion' => 'Renovación de Licenciamiento',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '11',
            ],
            11 => [
                'id' => 12,
                'descripcion' => 'Consultoria',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '12',
            ],
            12 => [
                'id' => 13,
                'descripcion' => 'Actividades de Venta y Promoción de Negocios',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '13',
            ],
            13 => [
                'id' => 14,
                'descripcion' => 'Arrendamiento de equipos de cómputo',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '14',
            ],
            14 => [
                'id' => 15,
                'descripcion' => 'Pago de bases para licitación',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '15',
            ],
            15 => [
                'id' => 16,
                'descripcion' => 'Fianzas',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '16',
            ],
            16 => [
                'id' => 17,
                'descripcion' => 'Seguros',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '17',
            ],
            17 => [
                'id' => 18,
                'descripcion' => 'Diseño para marketing',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '18',
            ],
            18 => [
                'id' => 19,
                'descripcion' => 'Servicio de Arrendamiento de Servidores',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '19',
            ],
            19 => [
                'id' => 20,
                'descripcion' => 'Servicio de Soporte Tecnico',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '20',
            ],
            20 => [
                'id' => 21,
                'descripcion' => 'Renovación de Software',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '21',
            ],
            21 => [
                'id' => 22,
                'descripcion' => 'Servicio de soporte telefónico',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '22',
            ],
            22 => [
                'id' => 23,
                'descripcion' => 'Servicio de administración del correo de voz',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '23',
            ],
            23 => [
                'id' => 24,
                'descripcion' => 'Servicio de Ciberseguridad y Consultoría',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '24',
            ],
            24 => [
                'id' => 25,
                'descripcion' => 'Certificaciones',
                'created_at' => '2023-08-16 18:28:38',
                'updated_at' => '2023-08-16 18:29:13',
                'deleted_at' => null,
                'archivo' => 0,
                'clave' => '25',
            ],
        ]);
    }
}
