<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProveedorOCSTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('proveedor_o_c_s')->delete();

        \DB::table('proveedor_o_c_s')->insert([
            0 => [
                'nombre' => 'Proveedores Varios Nacionales',
                'razon_social' => 'Proveedores Varios Nacionales',
                'rfc' => 'N/A',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-17 18:49:34',
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => '2023-08-17',
                'fecha_fin' => '2023-08-31',
            ],
            1 => [
                'nombre' => 'FAR SYSTEMS',
                'razon_social' => 'FAR SYSTEMS S.C.P',
                'rfc' => 'FSY0501188U8',
                'contacto' => 'Miriam Valencia',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            2 => [
                'nombre' => 'AURUM TECNOLOGIA',
                'razon_social' => 'Aurum Tecnología S.A de C.V',
                'rfc' => 'ATE130116Q28',
                'contacto' => 'Felipe Medina',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            3 => [
                'nombre' => 'AXTEL',
                'razon_social' => 'AXTEL S.A.B. DE C.V.',
                'rfc' => 'AXT940727FP8',
                'contacto' => 'ANA CECILIA AGUIRRE GONZALEZ',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            4 => [
                'nombre' => 'AyR',
                'razon_social' => 'AYR ENLACES EMPRESARIALES, S.A. DE C.V',
                'rfc' => 'AEE1605054P1',
                'contacto' => 'Lorena Piña Fuentes',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            5 => [
                'nombre' => 'ContPAQi',
                'razon_social' => 'HUGO GONZALEZ GUERRA',
                'rfc' => 'GUGH791023DD0',
                'contacto' => 'MARIA CONSUELO TULE JIMENEZ',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            6 => [
                'nombre' => 'MS NOTARIO',
                'razon_social' => 'MS NOTARIO S.C',
                'rfc' => 'MNO930107ST1',
                'contacto' => 'Sarahi Castaneda',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            7 => [
                'nombre' => 'Notario 208',
                'razon_social' => 'N208 S.C',
                'rfc' => 'NXX1210186TA',
                'contacto' => 'Agustin Gutierrez Katze',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            8 => [
                'nombre' => 'Neixar MXN',
                'razon_social' => 'Neixar Systems S.A de C.V',
                'rfc' => 'NSY060512CS6',
                'contacto' => 'Guillermo Deloiza',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            9 => [

                'nombre' => 'NOTARIA',
                'razon_social' => 'NOTARIA REFORMA 420 S.C.',
                'rfc' => 'NVE130306IT3',
                'contacto' => 'Lilia Reforma',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            10 => [

                'nombre' => 'OFFICE DEPOT',
                'razon_social' => 'OFFICE DEPOT DE MÉXICO S.A DE C.V',
                'rfc' => 'ODM950324V2A',
                'contacto' => 'Fabiola Pamela López Balbuena',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            11 => [

                'nombre' => 'Online MÉXICO',
                'razon_social' => 'Online Career Center MÉXICO S.API de C.V',
                'rfc' => 'OCC9611015V7',
                'contacto' => 'Beatriz Cardenas',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            12 => [

                'nombre' => 'ESTRATEC',
                'razon_social' => 'ESTRATEC SA DE CV',
                'rfc' => 'EST850718Q51',
                'contacto' => 'LUIS KEN OHARA KONDO',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            13 => [

                'nombre' => 'Zurich',
                'razon_social' => 'Zurich Cia de Seguros S.A.',
                'rfc' => 'ZSE950306M48',
                'contacto' => 'Claudine Seguros',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            14 => [

                'nombre' => 'PASE',
                'razon_social' => 'PASE, SERVICIOS ELECTRÓNICOS S.A DE C.V',
                'rfc' => 'ISD950921HE5',
                'contacto' => 'KaR.La Renta Michel Pacheco',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            15 => [

                'nombre' => 'NUBAJ',
                'razon_social' => 'NUBAJ S.A. DE C.V.',
                'rfc' => 'NUB130904HN0',
                'contacto' => 'LYSETTE MAYEN SILVA',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            16 => [

                'nombre' => 'Aseguradora Aserta SA de CV',
                'razon_social' => 'Aseguradora Aserta SA de CV',
                'rfc' => 'AAS9207314T7',
                'contacto' => 'ULISES RIVERA R',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            17 => [

                'nombre' => 'COMERCIALIZADORA DE VALOR AGREGADO S.A DE C.V',
                'razon_social' => 'COMERCIALIZADORA DE VALOR AGREGADO S.A DE C.V',
                'rfc' => 'CVA9904266T9',
                'contacto' => 'Oscar Canales Contreras',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            18 => [

                'nombre' => 'COMPUSOLUCIONES Y ASOCIADOS SA DE CV',
                'razon_social' => 'COMPUSOLUCIONES Y ASOCIADOS SA DE CV',
                'rfc' => 'CAS850526N64',
                'contacto' => 'Alejandra Real',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            19 => [

                'nombre' => 'DKTM',
                'razon_social' => 'DKTM SC',
                'rfc' => 'DKV091106JI7',
                'contacto' => 'SONIA FERNANDEZ',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            20 => [

                'nombre' => 'GRUPO DICE SA DE CV',
                'razon_social' => 'GRUPO DICE SA DE CV',
                'rfc' => 'GDI880315IYA',
                'contacto' => 'SANDRA BERROETA',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-14 16:55:06',
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => '2023-08-14',
                'fecha_fin' => '2023-08-15',
            ],
            21 => [

                'nombre' => 'INGRAM',
                'razon_social' => 'INGRAM MICRO MEXICO, S.A. DE C.V',
                'rfc' => 'IMM9304016Z4',
                'contacto' => 'GILBERTO NANCO',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            22 => [

                'nombre' => 'MAAT',
                'razon_social' => 'Maat Asesores SC',
                'rfc' => 'MAS171023M71',
                'contacto' => 'JORGE A. FERNÁNDEZ I.',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            23 => [

                'nombre' => 'MAPS',
                'razon_social' => 'MAYORISTAS DE PARTES Y SERVICIOS .SA de C.V',
                'rfc' => 'MPS920227IL9',
                'contacto' => 'Elsa Gallegos',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-16 19:53:15',
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => '2023-08-16',
                'fecha_fin' => '2023-08-21',
            ],
            24 => [

                'nombre' => 'ORBEN',
                'razon_social' => 'ORBEN COMUNICACIONES SAPI DE CV',
                'rfc' => 'OCO9804024E6',
                'contacto' => 'Flor Cedeño Plascencia',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            25 => [

                'nombre' => 'WESTCON',
                'razon_social' => 'WESTCON MEXICO S.A DE C.V',
                'rfc' => 'WME000218GK3',
                'contacto' => 'RAUL NAVARRO',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            26 => [

                'nombre' => 'WISE',
                'razon_social' => 'WISE SOLUTIONS SA DE CV',
                'rfc' => 'WSO070403QP1',
                'contacto' => 'Jorge Ernesto Cuéllar Martínez',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            27 => [

                'nombre' => 'X WEB',
                'razon_social' => 'X WEB SA DE CV',
                'rfc' => 'XWE0102149Q4',
                'contacto' => 'Edgardo Calderón',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            28 => [

                'nombre' => 'XALINA',
                'razon_social' => 'JUAN RAMON CHAN AQUINO',
                'rfc' => 'CAAJ7409038M9',
                'contacto' => 'Juan Ramon Chan Aquino',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            29 => [

                'nombre' => 'VAINDEC',
                'razon_social' => 'Vaindec SA de CV',
                'rfc' => 'VAI1409222H1',
                'contacto' => 'Herman Rosso',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            30 => [

                'nombre' => 'BMP CPNSULTORES',
                'razon_social' => 'BMP CONSULTORES SA DE CV',
                'rfc' => 'BCO140411M76',
                'contacto' => 'Vista Linda',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            31 => [

                'nombre' => 'KAIZEN',
                'razon_social' => 'Kaizen Soluciones TIC, S.A. de C.V.',
                'rfc' => 'KST150518K37',
                'contacto' => 'Arturo García-Naranjo y Cinca',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            32 => [

                'nombre' => 'ADMI PROCESOS',
                'razon_social' => 'ADMINISTRACION DE PROCESOS DE TRANSFORMACION',
                'rfc' => 'APT050613TQ6',
                'contacto' => 'Lorena Pina',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            33 => [

                'nombre' => 'CESCE FIANZAS',
                'razon_social' => 'CESCE FIANZAS MEXICO SA DE CV',
                'rfc' => 'CFM1008302NA',
                'contacto' => 'Victor Vargas',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-17 14:04:08',
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => '2022-11-18',
                'fecha_fin' => '2023-01-29',
            ],
            34 => [

                'nombre' => 'Ortiz Linares',
                'razon_social' => 'Ortiz Linares Abogados Asociados S C',
                'rfc' => 'OLA121130DG7',
                'contacto' => 'Miguel Angel Linares',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            35 => [

                'nombre' => 'SACRESA',
                'razon_social' => 'Sacresa Consultores SA de CV',
                'rfc' => 'SCO1103166EA',
                'contacto' => 'Angeles Garcia',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            36 => [

                'nombre' => 'JACQUES',
                'razon_social' => 'SERVICIOS DE CONSULTORIA JURIDICA JACQUES FONTAINE S DE R.L D',
                'rfc' => 'SCJ150226HCA',
                'contacto' => 'Ariadna Aguilar',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            37 => [

                'nombre' => 'Rayn Tech',
                'razon_social' => 'Rayn Tech SA de CV',
                'rfc' => 'RTE160922F37',
                'contacto' => 'Miriam Klein',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            38 => [

                'nombre' => 'CONSEIL D AFFAIRES BELAYAGE SA DE CV',
                'razon_social' => 'CONSEIL D AFFAIRES BELAYAGE SA DE CV',
                'rfc' => 'CDA160427NP3',
                'contacto' => 'JENNY RIVERA',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            39 => [

                'nombre' => 'Cyberpuerta SA de CV',
                'razon_social' => 'Cyberpuerta SA de CV',
                'rfc' => 'CYB080602ISA',
                'contacto' => 'Oscar Joaquin Gutierrez',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            40 => [

                'nombre' => 'Estrategias BETA S.C.',
                'razon_social' => 'Estrategias BETA S.C.',
                'rfc' => 'EBE121221671',
                'contacto' => 'Serafin Lugo Martinez',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            41 => [

                'nombre' => 'CFE SUMINISTRADOR DE SERVICIOS BASICOS',
                'razon_social' => 'CFE SUMINISTRADOR DE SERVICIOS BASICOS',
                'rfc' => 'CSS160330CP7',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            42 => [

                'nombre' => 'BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BANCA MULTIPLE GRUPO FINANCIERO BANORTE',
                'razon_social' => 'BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BANCA MULTIPLE GRUPO FINANCIERO BANORTE',
                'rfc' => 'BMN930209927',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            43 => [

                'nombre' => 'DCH Global SA de CV',
                'razon_social' => 'DCH Global SA de CV',
                'rfc' => 'DGL151201382',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            44 => [

                'nombre' => 'ANCIANO Y AYALA ABOGADOS, S.C.',
                'razon_social' => 'ANCIANO Y AYALA ABOGADOS, S.C.',
                'rfc' => 'AAA070921TB9',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            45 => [

                'nombre' => 'TELEFONOS DE MEXICO S.A.B. DE C.V.',
                'razon_social' => 'TELEFONOS DE MEXICO S.A.B. DE C.V.',
                'rfc' => 'TME840315KT6',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            46 => [

                'nombre' => 'APPLE',
                'razon_social' => 'APPLE OPERATIONS MEXICO SA DE CV',
                'rfc' => 'AOM920820BEA',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            47 => [

                'nombre' => 'FREIGHT IDEAS SA DE CV',
                'razon_social' => 'FREIGHT IDEAS SA DE CV',
                'rfc' => 'FID080111867',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            48 => [

                'nombre' => 'GLOBAL STD',
                'razon_social' => 'GLOBAL STANDARDS S.C',
                'rfc' => 'GST080421UT4',
                'contacto' => 'Tatiana Jerónimo',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            49 => [

                'nombre' => 'NOTARIA 201 S.C.',
                'razon_social' => 'NOTARIA 201 S.C.',
                'rfc' => 'NDU161018QEA',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            50 => [

                'nombre' => 'DELETE TECNOLOGY, SA DE CV',
                'razon_social' => 'DELETE TECNOLOGY, SA DE CV',
                'rfc' => 'SBL1008258T0',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            51 => [

                'nombre' => 'Servicios en Limpieza y Mantenimiento DANFER SA de CV',
                'razon_social' => 'Servicios en Limpieza y Mantenimiento DANFER SA de CV',
                'rfc' => 'SLM121017V35',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            52 => [

                'nombre' => 'GBT TRAVEL SERVICES MEXICO S DE RL DE CV',
                'razon_social' => 'GBT TRAVEL SERVICES MEXICO S DE RL DE CV',
                'rfc' => 'GTS131114AL9',
                'contacto' => 'MELISSA MORLET',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            53 => [

                'nombre' => 'AFH CONSULTORES Y ASOCIADOS S.C.',
                'razon_social' => 'AFH CONSULTORES Y ASOCIADOS S.C.',
                'rfc' => 'AFH9301258P2',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            54 => [

                'nombre' => 'UNIVERSIDAD DE LAS AMERICAS, A.C.',
                'razon_social' => 'UNIVERSIDAD DE LAS AMERICAS, A.C.',
                'rfc' => 'UAM630613SM7',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            55 => [

                'nombre' => 'LAS MEJORES EMPRESAS PARA TRABAJAR SAPI DE CV',
                'razon_social' => 'LAS MEJORES EMPRESAS PARA TRABAJAR SAPI DE CV',
                'rfc' => 'GPT030828U24',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            56 => [

                'nombre' => 'COMUNICACIÓN INTELIGENTE CBM SA DE CV',
                'razon_social' => 'COMUNICACIÓN INTELIGENTE CBM SA DE CV',
                'rfc' => 'CIC161018JC8',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            57 => [

                'nombre' => 'AF SERVICIOS SGMM',
                'razon_social' => 'AF SERVICIOS SGMM SA DE CV',
                'rfc' => 'XAX010101000',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            58 => [

                'nombre' => 'FUNDACIÓN POLITECNICO',
                'razon_social' => 'FUNDACIÓN POLITECNICO AC',
                'rfc' => 'FPO960828SY0',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            59 => [

                'nombre' => 'FARCIERT',
                'razon_social' => 'FARCIERT FLORES Y CIA SC',
                'rfc' => 'FFL901019NM9',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            60 => [

                'nombre' => 'DHL EXPRESS MEXICO S.A. DE C.V.',
                'razon_social' => 'DHL EXPRESS MEXICO S.A. DE C.V.',
                'rfc' => 'DEM8801152E9',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            61 => [

                'nombre' => 'OPERADORA OMX S.A. DE C.V.',
                'razon_social' => 'OPERADORA OMX S.A. DE C.V.',
                'rfc' => 'OOM960429832',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            62 => [

                'nombre' => 'HDI SEGUROS SA DE CV',
                'razon_social' => 'HDI SEGUROS SA DE CV',
                'rfc' => 'HSE701218532',
                'contacto' => 'Margarita Garcia Quiroz',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            63 => [

                'nombre' => 'ASOCIACIÓN NACIONAL DE UNIVERSIDADES E INSTITUCIONES DE EDUCACIÓN SUPERIOR DE LA REPÚBLICA MEXICANA',
                'razon_social' => 'ASOCIACIÓN NACIONAL DE UNIVERSIDADES E INSTITUCIONES DE EDUCACIÓN SUPERIOR DE LA REPÚBLICA MEXICANA',
                'rfc' => 'ANU930617MQ5',
                'contacto' => 'FROYLÁN LÓPEZ VALENCIA',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            64 => [

                'nombre' => 'Avelina Mayela Ramirez Rivera',
                'razon_social' => 'Avelina Mayela Ramirez Rivera',
                'rfc' => 'RARA701016BJ5',
                'contacto' => 'MAYELA RAMIREZ RIVERA',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            65 => [

                'nombre' => 'UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO',
                'razon_social' => 'UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO',
                'rfc' => 'UNA2907227Y5',
                'contacto' => 'Lic. Yazmin Barrales Zarza',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            66 => [

                'nombre' => 'RADIOMOVIL DIPSA SA DE CV',
                'razon_social' => 'RADIOMOVIL DIPSA SA DE CV',
                'rfc' => 'RDI841003QJ4',
                'contacto' => 'ITZHEL MOUEL OVIEDO',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            67 => [

                'nombre' => 'Asociación Mexicana de Lucha Contra el Cáncer A.C.',
                'razon_social' => 'Asociación Mexicana de Lucha Contra el Cáncer A.C.',
                'rfc' => 'AML7204246A1',
                'contacto' => 'Araceli Carreto Ortíz',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            68 => [

                'nombre' => 'AMERICAN EXPRESS COMPANY (MEXICO), S.A. DE C.V.',
                'razon_social' => 'AMERICAN EXPRESS COMPANY (MEXICO), S.A. DE C.V.',
                'rfc' => 'aec810901298',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            69 => [

                'nombre' => 'SOCIEDAD PANAMERICANA DE ESTUDIOS EMPRESARIALES, A.C.',
                'razon_social' => 'SOCIEDAD PANAMERICANA DE ESTUDIOS EMPRESARIALES, A.C.',
                'rfc' => 'spe661112kj4',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            70 => [

                'nombre' => 'ANTONIO ROSADO SÁNCHEZ',
                'razon_social' => 'ANTONIO ROSADO SÁNCHEZ',
                'rfc' => 'rosa381127qh2',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            71 => [

                'nombre' => 'INTELICOMP S.A DE C.V',
                'razon_social' => 'INTELICOMP S.A DE C.V',
                'rfc' => 'INT031028KA5',
                'contacto' => 'JESUS JOSUE VALENCIA GARCIA',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            72 => [

                'nombre' => 'CHUBB',
                'razon_social' => 'CHUBB SEGUROS MEXICO SA',
                'rfc' => 'ASE901221SM4',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            73 => [

                'nombre' => 'INSTITUTO SUPERIOR DE ESTUDIOS FISCALES A.C.',
                'razon_social' => 'INSTITUTO SUPERIOR DE ESTUDIOS FISCALES A.C.',
                'rfc' => 'ISE751222215',
                'contacto' => 'Vianey Osorio Olivera',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
            74 => [

                'nombre' => 'Soluciones Integrales en Capacitación S.A. de C.V.',
                'razon_social' => 'Soluciones Integrales en Capacitación S.A. de C.V.',
                'rfc' => 'SIC980401K73',
                'contacto' => 'Ingrid Dayeli Colin Sanabria',
                'estado' => 0,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'facturacion' => null,
                'direccion' => null,
                'envio' => null,
                'credito' => null,
                'fecha_inicio' => null,
                'fecha_fin' => null,
            ],
        ]);
    }
}
