<?php

namespace Database\Seeders;

use App\Models\TimesheetCliente;
use Illuminate\Database\Seeder;

class ProveedoresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('timesheet_clientes')->insert(array(
            0 =>
            array(
                'calle' => 'Insurgentes Sur',
                'celular_contacto' => NULL,
                'ciudad' => 'México',
                'cobertura' => NULL,
                'codigo_postal' => '07850',
                'colonia' => 'Atizapan',
                'correo_contacto' => NULL,
                'created_at' => '2022-02-15 15:22:01',
                'id_old' => 1,
                'id_fiscale' => NULL,
                'nombre' => 'test',
                'nombre_contacto' => 'Miguel Ángel Gaspar',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => NULL,
                'razon_social' => 'Silent4Business S.A de C.V',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2022-02-15 16:33:14',
            ),
            1 =>
            array(
                'calle' => 'Vito Alesio Robles #147',
                'celular_contacto' => NULL,
                'ciudad' => 'Álvaro Obregón, Ciudad de México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '01030',
                'colonia' => 'Colonia Florida',
                'correo_contacto' => NULL,
                'created_at' => '2022-02-17 13:23:39',
                'id_old' => 2,
                'id_fiscale' => NULL,
                'nombre' => 'SENER',
                'nombre_contacto' => 'Lic. José Isabel Díaz Pérez',
                'objeto_descripcion' => 'Conducir la política energética del país, dentro del marco constitucional vigente, de alta calidad económicamente viable y ampliamente sustentable de energéticos  que requiere el  desarrollo de la vida nacional.',
                'pagina_web' => 'https://www.gob.mx/sener',
                'puesto_contacto' => 'Director General de Recursos Humanos, Materiales y Servicios Generales',
                'razon_social' => 'Secretaría de Energía',
                'rfc' => 'SEN9412287J6',
                'telefono' => NULL,
                'updated_at' => '2022-02-17 13:23:39',
            ),
            2 =>
            array(
                'calle' => 'Periférico Blvd. Manuel Ávila Camacho #36',
                'celular_contacto' => NULL,
                'ciudad' => 'Miguel Hidalgo, Ciudad de México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '11000',
                'colonia' => 'Lomas - Virreyes, Lomas de Chapultepec',
                'correo_contacto' => NULL,
                'created_at' => '2022-02-17 13:48:04',
                'id_old' => 3,
                'id_fiscale' => NULL,
                'nombre' => 'Brasken Idesa',
                'nombre_contacto' => 'Jaime Flores Álvarez / Carlos Ernesto Ángeles Novoa',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.braskemidesa.com.mx',
                'puesto_contacto' => 'Representantes Legales',
                'razon_social' => 'Braskem Idesa S.A.P.I.',
                'rfc' => 'BID100428IX6',
                'telefono' => NULL,
                'updated_at' => '2022-02-17 13:48:04',
            ),
            3 =>
            array(
                'calle' => 'Insurgentes Sur #1143',
                'celular_contacto' => NULL,
                'ciudad' => 'Benito Juárez, Ciudad de México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '03720',
                'colonia' => 'Colonia Nochebuena',
                'correo_contacto' => NULL,
                'created_at' => '2022-02-17 15:08:38',
                'id_old' => 4,
                'id_fiscale' => NULL,
                'nombre' => 'IFT',
                'nombre_contacto' => 'Juan Carlos Jiménez Ángeles',
                'objeto_descripcion' => 'Desarrollo eficiente de la radio difusión y las telecomunicaciones a los dispuesto por la Ley Federal de Telecomunicaciones y Radiodifusión y tiene a su cargo la  regulación, promoción y supervisión del uso, aprovechamiento y explotación del espectro radioeléctrico, las redes y la prestación de los servicios de radiodifusión  y telecomunicaciones, además de ser la autoridad en materia de competencia económica en dichos sectores.',
                'pagina_web' => 'http://www.ift.org.mx',
                'puesto_contacto' => 'Director General de Adquisiciones Recursos Materiales y Servicios Generales',
                'razon_social' => 'Instituto Nacional de Telecomunicaciones',
                'rfc' => 'IFD130924CX1',
                'telefono' => NULL,
                'updated_at' => '2022-02-17 15:08:38',
            ),
            4 =>
            array(
                'calle' => 'Av. Insurgentes Sur#1999',
                'celular_contacto' => NULL,
                'ciudad' => 'Ciudad de México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '01020',
                'colonia' => 'Guadalupe Inn',
                'correo_contacto' => NULL,
                'created_at' => NULL,
                'id_old' => 5,
                'id_fiscale' => NULL,
                'nombre' => 'Royal Holiday Vacation Club',
                'nombre_contacto' => 'Carlos Javier de la Rosa',
                'objeto_descripcion' => 'Servicios de apoyo a los negocios que agrupa Unidades económicas dedicadas principalmente a proporcionar servicios de apoyo a los negocios, como administración de negocios, contratación y colocación de personal, apoyo secretarial, fotocopiado, cobranza, investigación crediticia, organización de viajes, investigación, protección y seguridad, limpieza, empacado y etiquetado de bienes propiedad de terceros, y organización de convenciones y ferias comerciales e industriales. Incluye también: u.e.d.p. a la consultaría en búsqueda de ejecutivos',
                'pagina_web' => 'http://royal-holiday.com',
                'puesto_contacto' => 'Gerente de Infraestructura y Operación',
                'razon_social' => 'Vacation Travel Advisory S.A. de C.V.',
                'rfc' => 'VTA140911DP6',
                'telefono' => '5556278880',
                'updated_at' => '2022-03-15 13:46:25',
            ),
            5 =>
            array(
                'calle' => 'Av. Paseo de la Reforma # 255',
                'celular_contacto' => 'NULL',
                'ciudad' => 'Ciudad de México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '06500',
                'colonia' => 'Juárez',
                'correo_contacto' => 'NULL',
                'created_at' => NULL,
                'id_old' => 6,
                'id_fiscale' => NULL,
                'nombre' => 'Bolsa Mexicana de Valores',
                'nombre_contacto' => 'Ramón Güemez Sarre ',
                'objeto_descripcion' => 'Esta empresa esta clasificada dentro del sector (523 - Actividades bursátiles, cambiarias y de inversión financiera que agrupa Unidades económicas dedicadas principalmente a operar en el mercado bursátil (bolsa de valores, casas de bolsa), a las operaciones de compra-venta de divisas, a la asesoría en inversiones en el mercado de valores, y otros servicios relacionados con la intermediación bursátil. Incluye también: u.e.d.p. al envío de dinero. Excluye: u.e.d.p. a la consultoría en administración, y en economía (541, Servicios profesionales, científicos y técnicos).',
                'pagina_web' => 'http://www.bmv.com.mx',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Bolsa Mexicana de Valores S.A.B. de C.V.',
                'rfc' => 'BMV760203JD4',
                'telefono' => '5553429000',
                'updated_at' => NULL,
            ),
            6 =>
            array(
                'calle' => 'Torre New York Life, Paseo de la Reforma  #342, Piso 42',
                'celular_contacto' => NULL,
                'ciudad' => 'Ciudad de México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '06600',
                'colonia' => 'Juárez',
                'correo_contacto' => NULL,
                'created_at' => NULL,
                'id_old' => 7,
                'id_fiscale' => NULL,
                'nombre' => 'SEMPRA',
                'nombre_contacto' => 'Carlos Ruiz  Sacristán',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'http://ienova.com.mx',
                'puesto_contacto' => 'Presidente del Consejo de Administració y Presidente Ejecutivo de IENOVA',
                'razon_social' => 'Infraestructura  Energética Nova S.A.B. de C.V.',
                'rfc' => 'SEM960419FL1',
                'telefono' => '5591380100',
                'updated_at' => '2023-01-19 14:16:48',
            ),
            7 =>
            array(
                'calle' => 'Av. Paseo de la Reforma # 243 Piso 21',
                'celular_contacto' => NULL,
                'ciudad' => 'Ciudad de México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '06500',
                'colonia' => 'Cuauhtémoc',
                'correo_contacto' => NULL,
                'created_at' => NULL,
                'id_old' => 8,
                'id_fiscale' => NULL,
                'nombre' => 'BXM',
                'nombre_contacto' => 'Humberto Goycoolea Heredía',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'http://www.vepormas.com',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Banco va por más, .S.A, Institución de Banca Multiple Grupo Financiero Ve por más',
                'rfc' => 'BVM951002LX0',
                'telefono' => '5511021800',
                'updated_at' => '2022-03-09 17:06:08',
            ),
            8 =>
            array(
                'calle' => 'Carretera Picacho - Ajusto # 167',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Tlalpan, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '14110',
                'colonia' => 'Col. Ampliación Fuentes del Pedregal',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-05 13:18:16',
                'id_old' => 9,
                'id_fiscale' => NULL,
                'nombre' => 'ASF',
                'nombre_contacto' => 'Lic. José Ignacio Silva Maquez',
                'objeto_descripcion' => 'La Auditoría Superior de la Federación (ASF) es el órgano técnico especializado de la Cámara de Diputados, dotado de autonomía técnica y de gestión, se encarga de fiscalizar el uso de los recursos públicos federales en los tres Poderes de la Unión; los órganos constitucionales autónomos; los estados y municipios; y en general cualquier entidad, persona física o moral, pública o privada que haya captado, recaudado, administrado, manejado o ejercido recursos públicos federales. El resultado final de la labor de la ASF son los Informes Individuales de Auditoría y el Informe General Ejecutivo del Resultado de la Fiscalización Superior de la Cuenta Pública.',
                'pagina_web' => 'https://www.asf.gob.mx',
                'puesto_contacto' => 'Director General de Recursos Materiales y Servicios',
                'razon_social' => 'AUDITORIA SUPERIOR DE LA FEDERACIÓN',
                'rfc' => 'ASF001230TS2',
                'telefono' => NULL,
                'updated_at' => '2022-07-08 09:44:58',
            ),
            9 =>
            array(
                'calle' => 'Prolongación Paseo de la Reforma',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón',
                'cobertura' => NULL,
                'codigo_postal' => '01210',
                'colonia' => 'Peña Blanca Santa Fe',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-11 09:25:54',
                'id_old' => 10,
                'id_fiscale' => NULL,
                'nombre' => 'BIMBO',
                'nombre_contacto' => 'Luis Miguel Briola Clement',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.grupobimbo.com',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Corporativo BIMBO, S.A. de C.V.',
                'rfc' => 'BIM011108DJ5',
                'telefono' => '52686600',
                'updated_at' => '2022-05-11 09:25:54',
            ),
            10 =>
            array(
                'calle' => 'Avenida Paseo de la Reforma # 135',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Cuauhtémoc, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '06030',
                'colonia' => 'Tabacalera',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-11 09:35:38',
                'id_old' => 11,
                'id_fiscale' => NULL,
                'nombre' => 'Cámara de Senadores',
                'nombre_contacto' => 'Lic. Miguel Ángel Dávila Narvaez',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.senado.gob.mx',
                'puesto_contacto' => 'Director General de Recursos Materiales y Servicios Generales',
                'razon_social' => 'CÁMARA DE SENADORES DEL H. CONGRESO DE LA UNIÓN',
                'rfc' => 'CSE750917BG3',
                'telefono' => NULL,
                'updated_at' => '2022-05-11 09:35:38',
            ),
            11 =>
            array(
                'calle' => 'Avenida Insurgentes Sur # 489',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Cuauhtémoc, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '06100',
                'colonia' => 'Hipódromo Condesa',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-13 14:26:50',
                'id_old' => 12,
                'id_fiscale' => NULL,
                'nombre' => 'SENASICA',
                'nombre_contacto' => 'Ing. Francisco Javier Calderón Elizalde',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.gob.mx/senasica',
                'puesto_contacto' => 'Director General de Administración e Informática',
                'razon_social' => 'SERVICIO NACIONAL DE SANIDAD, INOCUIDAD Y CALIDAD AGROALIMENTARIA',
                'rfc' => 'SNS960412AH4',
                'telefono' => NULL,
                'updated_at' => '2022-05-13 14:26:50',
            ),
            12 =>
            array(
                'calle' => 'Barranca del Muerto 280',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '01029',
                'colonia' => 'Guadalupe Inn',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-16 13:57:40',
                'id_old' => 13,
                'id_fiscale' => NULL,
                'nombre' => 'INFONAVIT',
                'nombre_contacto' => 'Salvador Raúl González Reyna',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.portalmx.infonavit.org.mx',
                'puesto_contacto' => 'Subdirector General de Tecnologías de Información',
                'razon_social' => 'Instituto de Fondo Nacional de la Vivienda para los Trabajadores',
                'rfc' => 'Y64471134103',
                'telefono' => NULL,
                'updated_at' => '2022-05-16 13:57:40',
            ),
            13 =>
            array(
                'calle' => 'Campus Corporativo Coyoacán Avenida Coyoacán #1622, Edificio 3PB',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Benito Juárez, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '03100',
                'colonia' => 'Del Valle Sur',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-16 17:06:47',
                'id_old' => 14,
                'id_fiscale' => NULL,
                'nombre' => 'HIXSA',
                'nombre_contacto' => 'Hugo Huerta Zarate',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://hixsa.com',
                'puesto_contacto' => 'Represente Legal',
                'razon_social' => 'Consultoría y Servicios en Tecnología HIX S.A. de C.V.',
                'rfc' => 'CST080221JP9',
                'telefono' => '55240014',
                'updated_at' => '2022-05-16 17:06:47',
            ),
            14 =>
            array(
                'calle' => 'Avenida Insurgentes Sur #1458, Piso 19 y 20',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Benito Juárez, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '03230',
                'colonia' => 'Actipan',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-17 13:19:21',
                'id_old' => 15,
                'id_fiscale' => NULL,
                'nombre' => 'DENTEGRA',
                'nombre_contacto' => 'Alejandro Dominguez',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.dentegra.com.mx',
                'puesto_contacto' => 'Project Manager',
                'razon_social' => 'Dentegra  Seguros Dentales S.A. de C.V.',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2022-05-17 13:19:21',
            ),
            15 =>
            array(
                'calle' => 'Alfonso Reyes Nte. #2202',
                'celular_contacto' => NULL,
                'ciudad' => 'Monterrey, Nuevo León',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '64410',
                'colonia' => 'Bella Vista',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-18 09:24:26',
                'id_old' => 16,
                'id_fiscale' => NULL,
                'nombre' => 'HEINEKEN',
                'nombre_contacto' => 'Carlos Olivas',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://cerveceriacuauhtemoc.com.mx',
                'puesto_contacto' => 'Project Manager',
                'razon_social' => 'Grupo Cuauhtémoc Moctezuma S.A. de C.V.',
                'rfc' => 'GCM960301469',
                'telefono' => NULL,
                'updated_at' => '2022-05-18 09:24:26',
            ),
            16 =>
            array(
                'calle' => 'Insurgentes Sur #1931',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '01020',
                'colonia' => 'Guadalupe Inn',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-18 12:44:25',
                'id_old' => 17,
                'id_fiscale' => NULL,
                'nombre' => 'INDEP',
                'nombre_contacto' => 'José Ángel Ansúrez Galicia',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.indep.gob.mx',
                'puesto_contacto' => 'Encargado de Despacho de la Dirección Ejecutiva de Recursos Materiales',
                'razon_social' => 'Insituto para devolver al pueblo lo robado',
                'rfc' => 'SAE030617SV8',
                'telefono' => NULL,
                'updated_at' => '2022-05-18 12:44:25',
            ),
            17 =>
            array(
                'calle' => 'Corporativo Banjercito Av. Industria Militar #1055',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Miguel Hidalgo, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '11200',
                'colonia' => 'Lomas de Sotelo',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-18 13:38:50',
                'id_old' => 18,
                'id_fiscale' => NULL,
                'nombre' => 'BANJERCITO',
                'nombre_contacto' => 'MYR I.C.E. Noe Nicolás Miguel',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.gob.mx/banjercito',
                'puesto_contacto' => 'Dirección de Área',
                'razon_social' => 'Banco Nacional del Ejercito, Fuerza Aérea y Armada, SNC.',
                'rfc' => 'BNE82901682',
                'telefono' => NULL,
                'updated_at' => '2022-05-18 13:38:50',
            ),
            18 =>
            array(
                'calle' => 'Carlota Armero 5000',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Coyoacán, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '04480',
                'colonia' => 'Col. CTM Culhuacán Sección VII',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-18 14:21:48',
                'id_old' => 19,
                'id_fiscale' => NULL,
                'nombre' => 'TEPJF',
                'nombre_contacto' => 'Lic. Arturo Camacho Contreras',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.trife.gob.mx',
                'puesto_contacto' => 'Director General de Adquisiciones Servicios y Obras Públicas',
                'razon_social' => 'Tribunal Electoral del Poder Judicial de la Federción',
                'rfc' => 'TEP961122B8A',
                'telefono' => NULL,
                'updated_at' => '2022-05-18 14:21:48',
            ),
            19 =>
            array(
                'calle' => 'Horacio  #1844 piso 8',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Miguel Hidalgo, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '11510',
                'colonia' => 'Polanco I Sección',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-19 10:21:48',
                'id_old' => 20,
                'id_fiscale' => NULL,
                'nombre' => 'KONFIO',
                'nombre_contacto' => 'Francisco de Jesús Padilla Sánchez',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://konfio.mx/',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Red Amigo DAL, S.A.P.I, SOFOM, EN.R.',
                'rfc' => 'RAD130627IH2',
                'telefono' => NULL,
                'updated_at' => '2022-05-19 10:21:48',
            ),
            20 =>
            array(
                'calle' => 'Calle Poniente 134 , No. 470',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Gustavo A. Madero, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '07700',
                'colonia' => 'Nueva Industrial Vallejo',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-19 12:20:44',
                'id_old' => 21,
                'id_fiscale' => NULL,
                'nombre' => 'COLTOMEX',
                'nombre_contacto' => 'José Antonio García Solis',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.coltomex.com/',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'COLTOMEX S.A. DE C.V.',
                'rfc' => 'COL130513JE1',
                'telefono' => NULL,
                'updated_at' => '2022-06-09 11:08:38',
            ),
            21 =>
            array(
                'calle' => 'Av. Melchor Ocampo 193, Torre Privanza, Piso 16',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Miguel Hidalgo, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '11300',
                'colonia' => 'Verónica Anzures',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-19 15:45:36',
                'id_old' => 22,
                'id_fiscale' => NULL,
                'nombre' => 'CINTEGRA',
                'nombre_contacto' => 'Carlos Cortes Domínguez',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://cintegra.mx',
                'puesto_contacto' => 'Project Manager',
                'razon_social' => 'Compañía Integra Soluciones, S.A. de .C.V.',
                'rfc' => 'ISO0601306W0',
                'telefono' => '5552552233',
                'updated_at' => '2022-05-19 15:45:36',
            ),
            22 =>
            array(
                'calle' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 123',
                'celular_contacto' => NULL,
                'ciudad' => 'sssssssssssssssss',
                'cobertura' => NULL,
                'codigo_postal' => '09876',
                'colonia' => 'sssssssssssssssss',
                'correo_contacto' => NULL,
                'created_at' => '2022-05-26 15:36:29',
                'id_old' => 23,
                'id_fiscale' => NULL,
                'nombre' => 'Solutec',
                'nombre_contacto' => 'Juan Mendez',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Gerente TI',
                'razon_social' => 'Soluciones tecno S.a. de C. V.',
                'rfc' => 'SOLU220578RP1',
                'telefono' => '4444444',
                'updated_at' => '2022-06-08 17:35:32',
            ),
            23 =>
            array(
                'calle' => 'Ave. Insurgentes Sur #1971',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '01020',
                'colonia' => 'Guadalupe Inn',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-08 17:16:35',
                'id_old' => 24,
                'id_fiscale' => NULL,
                'nombre' => 'CNSF',
                'nombre_contacto' => 'Jorge González Alvarado',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.gob.mx/cnsf',
                'puesto_contacto' => 'Director de Sistemas',
                'razon_social' => 'Comisión Nacional de Seguros y Fianzas',
                'rfc' => 'CNS901213D90',
                'telefono' => NULL,
                'updated_at' => '2022-06-08 17:16:35',
            ),
            24 =>
            array(
                'calle' => 'Ave. Insurgentes Sur #1425',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '03920',
                'colonia' => 'Insurgentes Mixcoac',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-08 17:34:51',
                'id_old' => 25,
                'id_fiscale' => NULL,
                'nombre' => 'STPMEX',
                'nombre_contacto' => 'José Refugio Gutiérrez Burciaga',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://stp.mx/',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Sistema de Transferencias y Pagos STP, S.A de C.V., SOFOM, E.N.R.',
                'rfc' => 'STP081030FE6',
                'telefono' => NULL,
                'updated_at' => '2022-06-08 17:44:50',
            ),
            25 =>
            array(
                'calle' => 'Calzada Legaria #542, Torre 2 Piso 7',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Miguel Hidalgo, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '11250',
                'colonia' => '10 de abril',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-08 17:53:14',
                'id_old' => 26,
                'id_fiscale' => NULL,
                'nombre' => 'VALMEX',
                'nombre_contacto' => 'Gustavo Raúl Uribe Hernández/ Claudia Álvarez Toledo',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.valmex.com.mx/',
                'puesto_contacto' => 'Representantes Legales',
                'razon_social' => 'Valores Mexicanos Casa de Bolsa, S.A. de C.V.',
                'rfc' => 'VMC980216FQ3',
                'telefono' => NULL,
                'updated_at' => '2022-06-08 17:53:14',
            ),
            26 =>
            array(
                'calle' => 'Calzada Manuel Gómez  Morin # 444',
                'celular_contacto' => NULL,
                'ciudad' => 'Torreón, Torreón México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '27268',
                'colonia' => 'Torreón Residencial',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-09 08:37:45',
                'id_old' => 27,
                'id_fiscale' => NULL,
                'nombre' => 'PEÑOLES',
                'nombre_contacto' => 'Ing. Rafael Rebollar Gónzalez',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.penoles.com.mx/',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Servicios Especializados Peñoles S.A de C.V.',
                'rfc' => 'SEP1312171X9',
                'telefono' => NULL,
                'updated_at' => '2022-07-11 09:21:17',
            ),
            27 =>
            array(
                'calle' => 'Paseo María Elena # 1129',
                'celular_contacto' => NULL,
                'ciudad' => 'Monterrey, Nuevo León, México',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '64750',
                'colonia' => 'Ampliación Valle del Mirador',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-09 09:11:21',
                'id_old' => 28,
                'id_fiscale' => NULL,
                'nombre' => 'IKUSI',
                'nombre_contacto' => 'Karolyn Luciana López Churata',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.ikusi.com/es/',
                'puesto_contacto' => 'Project Manager',
                'razon_social' => 'Micronet de México, S.A. de C.V.',
                'rfc' => 'MME000601MI17',
                'telefono' => NULL,
                'updated_at' => '2022-06-09 09:11:21',
            ),
            28 =>
            array(
                'calle' => 'Calle Poniente 134 #470',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Gustavo A. Madero, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '07700',
                'colonia' => 'Nueva Industrial Vallejo',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-09 11:07:45',
                'id_old' => 29,
                'id_fiscale' => NULL,
                'nombre' => 'COLTOMONEY',
                'nombre_contacto' => 'José Antonio García Solis',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.coltomex.com/',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'COLTOMONEY, S.A. DE C.V.',
                'rfc' => 'COL1612055Z5',
                'telefono' => NULL,
                'updated_at' => '2022-06-09 11:09:39',
            ),
            29 =>
            array(
                'calle' => 'Calle 3, Norte #102',
                'celular_contacto' => NULL,
                'ciudad' => 'Estado de México',
                'cobertura' => 'Republica Méxicana',
                'codigo_postal' => '50233',
                'colonia' => 'Col. Parque Industrial Toluca 2000',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-27 09:53:39',
                'id_old' => 30,
                'id_fiscale' => NULL,
                'nombre' => 'ARABELA',
                'nombre_contacto' => 'Salvador Hernández',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'http://www.arabela.com/',
                'puesto_contacto' => 'Gerente de Operación de Estructura',
                'razon_social' => 'ARABELA, S.A DE C.V.',
                'rfc' => 'ARA900710AX8',
                'telefono' => NULL,
                'updated_at' => '2022-06-27 10:04:41',
            ),
            30 =>
            array(
                'calle' => 'Sur #116',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '01120',
                'colonia' => 'Las Américas',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-27 14:03:17',
                'id_old' => 31,
                'id_fiscale' => NULL,
                'nombre' => 'Hospital ABC',
                'nombre_contacto' => 'Lic. Álvaro López Aldana',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://centromedicoabc.com/',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'The American British Cowdray Medical Center I.A.P.',
                'rfc' => 'ABC410704710',
                'telefono' => NULL,
                'updated_at' => '2022-06-27 14:03:17',
            ),
            31 =>
            array(
                'calle' => 'Ave. Insurgentes Sur #863 piso 2 y 3',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Benito Juárez, CDMX',
                'cobertura' => 'Republica Mexicana',
                'codigo_postal' => '03810',
                'colonia' => 'Napoles',
                'correo_contacto' => NULL,
                'created_at' => '2022-06-27 16:00:28',
                'id_old' => 32,
                'id_fiscale' => NULL,
                'nombre' => 'Farmacias San Pablo',
                'nombre_contacto' => 'Por asignar',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.farmaciasanpablo.com.mx/',
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'UNIFAR S.A. de C.V.',
                'rfc' => 'UNI000221LY7',
                'telefono' => NULL,
                'updated_at' => '2022-06-27 16:00:28',
            ),
            32 =>
            array(
                'calle' => 'Blvd. Adolfo Ruíz Cortines # 4308',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Coyoacán, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '04500',
                'colonia' => 'Ampliación Jardines de Pedregal',
                'correo_contacto' => 'jesus.martinez@casaagp.com',
                'created_at' => '2022-07-08 10:10:25',
                'id_old' => 33,
                'id_fiscale' => NULL,
                'nombre' => 'AGP HOLDING BC',
                'nombre_contacto' => 'Jesús Martínez Chávez',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'ADMINISTRADORA Y OPERADORA CIMSA S.A DE C.V.',
                'rfc' => 'AWS930329472',
                'telefono' => '5555689830',
                'updated_at' => '2022-07-08 10:10:25',
            ),
            33 =>
            array(
                'calle' => 'Ave. Heroe de Nacazori Sur No. 2301',
                'celular_contacto' => NULL,
                'ciudad' => 'Aguascalientes, Ags',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '20276',
                'colonia' => 'Fracc. Jardines del Parque',
                'correo_contacto' => NULL,
                'created_at' => '2022-07-08 11:51:53',
                'id_old' => 34,
                'id_fiscale' => NULL,
                'nombre' => 'INEGI',
                'nombre_contacto' => 'Lic. Víctor Manuel Rodríguez Silva',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.inegi.org.mx/',
                'puesto_contacto' => 'Director General Adjunto de Recursos Materiales y Servicios Generales',
                'razon_social' => 'INSTITUTO NACIONAL DE ESTADÍSTICA Y GEOGRAFÍA',
                'rfc' => 'INE0804164Z7',
                'telefono' => NULL,
                'updated_at' => '2022-07-08 11:51:53',
            ),
            34 =>
            array(
                'calle' => 'Ave. C.F.E. No. 200 Mzna 50',
                'celular_contacto' => NULL,
                'ciudad' => 'San Luis Potosí',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '78395',
                'colonia' => 'Zona Industrial  1ra. Sección',
                'correo_contacto' => 'rmoran@cmm.gob.mx',
                'created_at' => '2022-07-08 12:37:44',
                'id_old' => 35,
                'id_fiscale' => NULL,
                'nombre' => 'CASA DE MONEDA DE MEXICO',
                'nombre_contacto' => 'Felipe Rogelio Morán Izalde',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.gob.mx/cmm',
                'puesto_contacto' => 'Gerente de Informática',
                'razon_social' => 'CASA DE MONEDA DE MEXICO',
                'rfc' => 'CMM860120KI1',
                'telefono' => NULL,
                'updated_at' => '2022-07-08 12:37:44',
            ),
            35 =>
            array(
                'calle' => 'Ave. Insurgentes Sur # 1647',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '03900',
                'colonia' => 'San José Insurgentes',
                'correo_contacto' => 'gebutron@adamantine.com.mx',
                'created_at' => '2022-07-08 16:52:35',
                'id_old' => 36,
                'id_fiscale' => NULL,
                'nombre' => 'ADAMANTINE',
                'nombre_contacto' => 'Ing. Gerardo Enrique  Butron Medina',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.adamantine.com.mx/',
                'puesto_contacto' => 'Gerente de Infraestructura de TI',
                'razon_social' => 'ADAMANTINE SERVICIOS, S.A. DE C.V.',
                'rfc' => 'ASE120613F72',
                'telefono' => '5543443471',
                'updated_at' => '2022-07-08 16:52:35',
            ),
            36 =>
            array(
                'calle' => 'Anillo Periférico # 3307, San Jerónimo Lídice',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Magdalena Contreras, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '10200',
                'colonia' => 'Jardines del Pedregal',
                'correo_contacto' => NULL,
                'created_at' => '2022-07-11 09:13:03',
                'id_old' => 37,
                'id_fiscale' => NULL,
                'nombre' => 'INTERESSE',
                'nombre_contacto' => 'Carlos Puerto',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.interesse.com.mx/',
                'puesto_contacto' => 'CIO',
                'razon_social' => 'Grupo Interesse Agente de Seguros y Fianzas, S.A. de C.V.',
                'rfc' => 'IAS020102S4A',
                'telefono' => '5553370730',
                'updated_at' => '2022-07-11 09:13:03',
            ),
            37 =>
            array(
                'calle' => 'Ejercito Nacional #350, piso 3',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Miguel Hidalgo, CDMX',
                'cobertura' => 'Republica Mexicana',
                'codigo_postal' => '11560',
                'colonia' => 'Polanco V Sección',
                'correo_contacto' => NULL,
                'created_at' => '2022-07-11 16:05:27',
                'id_old' => 38,
                'id_fiscale' => NULL,
                'nombre' => 'SIEMENS',
                'nombre_contacto' => 'Ing. José Alberto Vélez Cortes',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://new.siemens.com/mx/es.html',
                'puesto_contacto' => 'Analista de Seguridad',
                'razon_social' => 'Siemens Servicios S.A. de C.V.',
                'rfc' => 'SIE931112PA1',
                'telefono' => NULL,
                'updated_at' => '2022-07-11 16:05:57',
            ),
            38 =>
            array(
                'calle' => 'Cerrada Palomas # 22 Int. 6',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Miguel Hidalgo, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '11650',
                'colonia' => 'Reforma Social',
                'correo_contacto' => NULL,
                'created_at' => '2022-07-11 16:51:31',
                'id_old' => 39,
                'id_fiscale' => NULL,
                'nombre' => 'GRUPO MODELO',
                'nombre_contacto' => 'Sergio Javier Apodaca Maldonado',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.grupomodelo.com/',
                'puesto_contacto' => 'Director de Seguridad',
                'razon_social' => 'Diblo Corporativo S.A. de C.V.',
                'rfc' => 'DCO8009185Y9',
                'telefono' => NULL,
                'updated_at' => '2022-07-11 16:51:31',
            ),
            39 =>
            array(
                'calle' => 'Río de la Magdalena #115',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '01090',
                'colonia' => 'Tizapán, San Angel',
                'correo_contacto' => NULL,
                'created_at' => '2022-08-10 16:38:22',
                'id_old' => 40,
                'id_fiscale' => NULL,
                'nombre' => 'BANCO DEL BIENESTAR (BANSEFI)',
                'nombre_contacto' => 'Lic. Antonio Ramírez Hernández',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.gob.mx/bancodelbienestar',
                'puesto_contacto' => 'Director General Adjunto de Administracion',
                'razon_social' => 'Banco del Bienestar, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo',
                'rfc' => 'BAN500901167',
                'telefono' => NULL,
                'updated_at' => '2022-08-10 16:38:22',
            ),
            40 =>
            array(
                'calle' => 'WORLD TRADE CENTER Montecito 38, Piso 5, Oficina 23',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Benito Juárez, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '03810',
                'colonia' => 'Napoles',
                'correo_contacto' => NULL,
                'created_at' => '2022-08-30 09:59:49',
                'id_old' => 41,
                'id_fiscale' => NULL,
                'nombre' => 'QS MEXIKO AG',
                'nombre_contacto' => 'Ing. Ernesto Fierro Félix',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.qsmexiko.com',
                'puesto_contacto' => NULL,
                'razon_social' => 'QS MEXIKO QS. AG. S.A. de C.V.',
                'rfc' => 'MQS010514API',
                'telefono' => '90003306',
                'updated_at' => '2022-08-30 09:59:49',
            ),
            41 =>
            array(
                'calle' => 'Adolfo López Mateos Np. 172, piso 3',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Benito Juárez, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '03930',
                'colonia' => 'Merced Gómez',
                'correo_contacto' => NULL,
                'created_at' => '2022-08-30 13:02:45',
                'id_old' => 42,
                'id_fiscale' => NULL,
                'nombre' => 'NUBAJ IT & CONSULTING',
                'nombre_contacto' => 'Enrique Cáliz  Morales',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.nubaj.com/',
                'puesto_contacto' => 'Project Manager',
                'razon_social' => 'Nubaj, S.A. de C.V.',
                'rfc' => NULL,
                'telefono' => '88521200',
                'updated_at' => '2022-08-30 13:02:45',
            ),
            42 =>
            array(
                'calle' => 'Avenida Insurgentes Sur 810',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Benito Juárez, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '03100',
                'colonia' => 'Del Valle',
                'correo_contacto' => NULL,
                'created_at' => '2022-09-22 16:02:26',
                'id_old' => 43,
                'id_fiscale' => NULL,
                'nombre' => 'CONEVAL',
                'nombre_contacto' => 'Daniel Gutierrez Cruz',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.coneval.org.mx/paginas/principal.aspx',
                'puesto_contacto' => 'Director General Adjunto',
                'razon_social' => 'Consejo Nacional de Evaluación de la Política de Desarrollo Social',
                'rfc' => 'CNE0508253Z4',
                'telefono' => NULL,
                'updated_at' => '2022-09-22 16:02:26',
            ),
            43 =>
            array(
                'calle' => 'Coronel Romero No. 1382 Int. B',
                'celular_contacto' => NULL,
                'ciudad' => 'San Luis Potosí',
                'cobertura' => 'San Luis Potosí',
                'codigo_postal' => '78369',
                'colonia' => 'Balcones del Valle',
                'correo_contacto' => NULL,
                'created_at' => '2022-09-22 16:56:56',
                'id_old' => 44,
                'id_fiscale' => NULL,
                'nombre' => 'COEP',
                'nombre_contacto' => 'Ing. Gerardo Serment Lazcano',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.coep.mx/',
                'puesto_contacto' => 'https://www.coep.mx/',
                'razon_social' => 'Cobranza Estratégica del Potosí ,S.C.',
                'rfc' => 'CEP1402221T4',
                'telefono' => NULL,
                'updated_at' => '2022-09-22 16:56:56',
            ),
            44 =>
            array(
                'calle' => 'Av. Congreso de la Unión # 66',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía  Venustiano Carranza, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '15960',
                'colonia' => 'El Parque',
                'correo_contacto' => NULL,
                'created_at' => '2022-09-23 17:35:52',
                'id_old' => 45,
                'id_fiscale' => NULL,
                'nombre' => 'Cámara de Diputados',
                'nombre_contacto' => 'Fernando Araiza Castañeda',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://web.diputados.gob.mx/inicio',
                'puesto_contacto' => 'Responsable del Centro de Cómputo y Seguridad Informática',
                'razon_social' => 'Honorable Cámara de Diputados',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2023-02-09 13:14:33',
            ),
            45 =>
            array(
                'calle' => 'Avenida de la República #35',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Cuauhtémoc, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '06030',
                'colonia' => 'Tabacalera',
                'correo_contacto' => NULL,
                'created_at' => '2022-09-27 11:16:54',
                'id_old' => 46,
                'id_fiscale' => NULL,
                'nombre' => 'SELEG',
                'nombre_contacto' => 'Nayeli Airaliith Escudero Sanchez',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'http://www.seleg.com.mx/index.html',
                'puesto_contacto' => 'Responsable del Proyecto',
                'razon_social' => 'SELEG COLLECTION & CONTACT CENTER',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2022-09-27 11:16:54',
            ),
            46 =>
            array(
                'calle' => 'Tonalá #60',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Cuauhtémoc, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '06700',
                'colonia' => 'Roma Norte',
                'correo_contacto' => NULL,
                'created_at' => '2022-09-27 15:11:38',
                'id_old' => 47,
                'id_fiscale' => NULL,
                'nombre' => 'ANDI',
                'nombre_contacto' => 'María Cristina Martínez C.',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'http://www.andi.org.mx/',
                'puesto_contacto' => 'Administración y Finanzas',
                'razon_social' => 'Asociación Nacional de Interpretes',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2022-09-27 15:11:38',
            ),
            47 =>
            array(
                'calle' => 'Bosques Alisos #47-B, Piso 4',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Cuajimalpa, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '05110',
                'colonia' => 'Bosques de las Lomas',
                'correo_contacto' => NULL,
                'created_at' => '2022-09-27 15:25:26',
                'id_old' => 48,
                'id_fiscale' => NULL,
                'nombre' => 'ELKAY',
                'nombre_contacto' => 'Francisco Miranda',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://latam.elkay.com/us/en.html',
                'puesto_contacto' => 'Project Manager',
                'razon_social' => 'Elkay Interior System Latin America S. de R.L. de C.V.',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2022-09-27 15:25:26',
            ),
            48 =>
            array(
                'calle' => 'Avenida de la Reforma #26',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Miguel Hidalgo, CDMX',
                'cobertura' => 'República Mexicana',
                'codigo_postal' => '006600',
                'colonia' => 'Tabacalera',
                'correo_contacto' => NULL,
                'created_at' => '2022-09-27 15:54:01',
                'id_old' => 49,
                'id_fiscale' => NULL,
                'nombre' => 'SEDATU',
                'nombre_contacto' => 'Marco Antonio Luna Robles (Provisional en que designan uno por parte de la SEDATU)',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.gob.mx/sedatu',
                'puesto_contacto' => 'Project Manager',
                'razon_social' => 'Secretaría de Desarrollo Agrario Territorial y Urbano',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2022-09-27 15:54:01',
            ),
            49 =>
            array(
                'calle' => 'Boulevard Adolfo Lopez Mateos 172',
                'celular_contacto' => '5515274603',
                'ciudad' => 'Benito Juarez',
                'cobertura' => NULL,
                'codigo_postal' => '03930',
                'colonia' => 'Merced Gomez',
                'correo_contacto' => 'guillermo.deloiza@neixar.com.mx',
                'created_at' => '2022-09-30 20:47:00',
                'id_old' => 50,
                'id_fiscale' => NULL,
                'nombre' => 'NEIXAR',
                'nombre_contacto' => 'Guillermo Deloiza Quintero',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://neixar.com/',
                'puesto_contacto' => 'Director de Finanzas',
                'razon_social' => 'NEIXAR SYSTEMS S.A. DE C.V.',
                'rfc' => 'NSY060512CS6',
                'telefono' => '5556047882',
                'updated_at' => '2022-09-30 20:47:00',
            ),
            50 =>
            array(
                'calle' => 'Av. Miguel de Cervantes Saavedra 233',
                'celular_contacto' => '5576872540',
                'ciudad' => 'Miguel Hidalgo',
                'cobertura' => NULL,
                'codigo_postal' => '11520',
                'colonia' => 'Granada',
                'correo_contacto' => 'irivng.arriaga@ironbit.com.mx',
                'created_at' => '2022-09-30 20:52:32',
                'id_old' => 51,
                'id_fiscale' => NULL,
                'nombre' => 'IRONBIT',
                'nombre_contacto' => 'Irving Arriaga',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Business Development Manager',
                'razon_social' => 'Digital Experiences S.A.P.I. de C.V',
                'rfc' => 'DEX140206K32',
                'telefono' => '5588523319',
                'updated_at' => '2022-09-30 20:52:32',
            ),
            51 =>
            array(
                'calle' => 'JAVIER BARROS SIERRA 540, TORRE II',
                'celular_contacto' => '3312994777',
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '01219',
                'colonia' => 'LOMAS DE SANTA FE',
                'correo_contacto' => 'p-dagomezm@bestel.com.mx',
                'created_at' => '2022-12-20 11:03:14',
                'id_old' => 52,
                'id_fiscale' => NULL,
                'nombre' => 'BESTEL',
                'nombre_contacto' => 'David Adriel Gomez Morales',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.bestel.com.mx/',
                'puesto_contacto' => 'Project Manager',
                'razon_social' => 'OPERBES',
                'rfc' => 'OPE070326DNA',
                'telefono' => '52612000',
                'updated_at' => '2023-01-06 13:26:39',
            ),
            52 =>
            array(
                'calle' => 'Paseo de la Reforma #234',
                'celular_contacto' => '5586876880',
                'ciudad' => 'Alcaldía Juárez, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '06600',
                'colonia' => 'Juárez',
                'correo_contacto' => 'aabrego@insignialife.com',
                'created_at' => '2022-12-20 14:56:42',
                'id_old' => 53,
                'id_fiscale' => NULL,
                'nombre' => 'INSIGNIA LIFE',
                'nombre_contacto' => 'Angélica Abrego Yañez',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.insignialife.com/',
                'puesto_contacto' => 'Directora',
                'razon_social' => 'INSIGNIA LIFE',
                'rfc' => 'ILI0805169R6',
                'telefono' => '5530883663',
                'updated_at' => '2022-12-20 14:56:42',
            ),
            53 =>
            array(
                'calle' => 'Carretera Tenayuca Santa Cecilia Avenida Acatitlán',
                'celular_contacto' => '5554038784',
                'ciudad' => 'Tlalnepantla de Baz',
                'cobertura' => NULL,
                'codigo_postal' => '54130',
                'colonia' => 'Santa Cecilia Acatitlán',
                'correo_contacto' => NULL,
                'created_at' => '2022-12-21 14:25:03',
                'id_old' => 54,
                'id_fiscale' => NULL,
                'nombre' => 'SYCOD',
                'nombre_contacto' => 'Enrique Vargas Santiago',
                'objeto_descripcion' => 'Renovación del licenciamiento de la plataforma INFOBLOX para ALSEA',
                'pagina_web' => 'https://www.sycod.com/',
                'puesto_contacto' => NULL,
                'razon_social' => 'Sistemas y Computadores Digitales, S.A. de C.V',
                'rfc' => 'SCD9402285U7',
                'telefono' => '5554038784',
                'updated_at' => '2022-12-21 14:25:03',
            ),
            54 =>
            array(
                'calle' => 'BOULEVARD ADOLFO LOPEZ MATEOS #2157',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Álvaro Obregón, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '01010',
                'colonia' => 'Los Alpes',
                'correo_contacto' => NULL,
                'created_at' => '2022-12-22 10:50:08',
                'id_old' => 55,
                'id_fiscale' => NULL,
                'nombre' => 'PENSIONISSSTE',
                'nombre_contacto' => 'Ing,. Ricardo Constantino López',
                'objeto_descripcion' => 'Servicio de Evaluación de Riesgo Tecnológico y Vulnerabilidades',
                'pagina_web' => NULL,
                'puesto_contacto' => 'Jefe de Servicios de Sistemas',
                'razon_social' => 'FONDO NACIONAL DE PENSIONES DE LOS TRABAJADORES AL SERVICIO DEL ESTADO',
                'rfc' => 'FNP070401RN9',
                'telefono' => NULL,
                'updated_at' => '2022-12-22 10:50:08',
            ),
            55 =>
            array(
                'calle' => 'Av. Insurgentes Sur 1458',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcandía Benito Juárez, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '03230',
                'colonia' => 'Actipan',
                'correo_contacto' => NULL,
                'created_at' => '2022-12-22 11:58:55',
                'id_old' => 56,
                'id_fiscale' => NULL,
                'nombre' => 'GENTERA',
                'nombre_contacto' => 'Ivonne Esquivel Rodriguez',
                'objeto_descripcion' => 'CONSULTORIA PROYECTO CERRADO SEGURIDAD (SERVICIO PRUEBAS DE INGENERIA SOCIAL)',
                'pagina_web' => NULL,
                'puesto_contacto' => NULL,
                'razon_social' => 'Compartamos Servicios SA de CV',
                'rfc' => 'CSE1107189H2',
                'telefono' => NULL,
                'updated_at' => '2022-12-22 11:58:55',
            ),
            56 =>
            array(
                'calle' => 'Volcán 150',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcandía Miguel Hidalgo, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '11000',
                'colonia' => 'LOMAS DE CHAPULTEPEC III SECCION',
                'correo_contacto' => 'jmendieta@n.technology',
                'created_at' => '2022-12-22 12:24:20',
                'id_old' => 57,
                'id_fiscale' => NULL,
                'nombre' => 'NTECH',
                'nombre_contacto' => 'Julio Mendieta Mariles',
                'objeto_descripcion' => 'Arrendamiento Publicación de servicio (IP PUBLICA)',
                'pagina_web' => NULL,
                'puesto_contacto' => NULL,
                'razon_social' => 'N DIGITAL EVOLUTION GROUP',
                'rfc' => 'CMG160421LG4',
                'telefono' => NULL,
                'updated_at' => '2022-12-22 12:45:30',
            ),
            57 =>
            array(
                'calle' => 'San Martín',
                'celular_contacto' => NULL,
                'ciudad' => 'Monterrey, Nuevo León',
                'cobertura' => NULL,
                'codigo_postal' => '64460',
                'colonia' => 'Mitras Centro',
                'correo_contacto' => 'suddireccion@assessorlegal.com',
                'created_at' => '2022-12-22 13:05:47',
                'id_old' => 58,
                'id_fiscale' => NULL,
                'nombre' => 'ABC ASSESSOR LEGAL CONSULTING',
                'nombre_contacto' => 'Tomas Orozco',
                'objeto_descripcion' => 'Servicios de Consultoria. Servicio de Concientización',
                'pagina_web' => NULL,
                'puesto_contacto' => 'Subdirector',
                'razon_social' => 'ABC ASSESSOR LEGAL CONSULTING',
                'rfc' => 'AAL090122S23',
                'telefono' => NULL,
                'updated_at' => '2022-12-22 13:05:47',
            ),
            58 =>
            array(
                'calle' => 'Boulevard Adolfo López Mateos #172',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Benito Juárez, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '03930',
                'colonia' => 'Merced Gómez',
                'correo_contacto' => NULL,
                'created_at' => '2022-12-26 14:39:34',
                'id_old' => 59,
                'id_fiscale' => NULL,
                'nombre' => 'CRE',
                'nombre_contacto' => 'Héctor Gustavo Aguirre Angulo',
                'objeto_descripcion' => 'Servicio de Operación de la Seguridad de la Información de la Comisión Reguladora de Energía',
                'pagina_web' => NULL,
                'puesto_contacto' => 'Director General de Tecnologías',
                'razon_social' => 'Comisión Reguladora de Energía',
                'rfc' => 'CRE9999999A9',
                'telefono' => NULL,
                'updated_at' => '2022-12-26 14:39:34',
            ),
            59 =>
            array(
                'calle' => 'Av. Ejército Nacional Mexicano 180',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcandía Miguel Hidalgo, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '11590',
                'colonia' => 'Anzures',
                'correo_contacto' => NULL,
                'created_at' => '2022-12-29 12:23:48',
                'id_old' => 60,
                'id_fiscale' => NULL,
                'nombre' => 'SFH',
                'nombre_contacto' => 'Default',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.gob.mx/shf',
                'puesto_contacto' => NULL,
                'razon_social' => 'SOCIEDAD HIPOTECARIA FEDERAL',
                'rfc' => NULL,
                'telefono' => '5552634500',
                'updated_at' => '2022-12-29 12:23:48',
            ),
            60 =>
            array(
                'calle' => 'Avenida Marina Nacional 329',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcandía Miguel Hidalgo, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '11311',
                'colonia' => 'Verónica Anzures',
                'correo_contacto' => NULL,
                'created_at' => '2023-01-06 14:40:39',
                'id_old' => 61,
                'id_fiscale' => NULL,
                'nombre' => 'PEMEX',
                'nombre_contacto' => 'Default',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://www.pemex.com/Paginas/default.aspx',
                'puesto_contacto' => NULL,
                'razon_social' => 'Petróleos Mexicanos S.A. de C.V.',
                'rfc' => 'PME380607P35',
                'telefono' => '5519442500',
                'updated_at' => '2023-01-06 14:40:39',
            ),
            61 =>
            array(
                'calle' => 'Viaducto Tlalpan 100',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcaldía Tlalpan, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '14610',
                'colonia' => 'Arenal Tepepan',
                'correo_contacto' => 'ariadna.galvan@ine.mx',
                'created_at' => '2023-01-11 15:15:37',
                'id_old' => 62,
                'id_fiscale' => NULL,
                'nombre' => 'INE',
                'nombre_contacto' => 'Ariadna Irais Galvan Vargas',
                'objeto_descripcion' => 'Organizar procesos electorales libres, equitativos y confiables, para garantizar el ejercicio de los derechos político-electorales de la ciudadanía y contribuir al desarrollo de la vida democrática de México.',
                'pagina_web' => 'https://ine.mx/',
                'puesto_contacto' => NULL,
                'razon_social' => 'INSTITUTO NACIONAL ELECTORAL',
                'rfc' => 'INE140404NI0',
                'telefono' => '8004332000',
                'updated_at' => '2023-01-11 15:15:37',
            ),
            62 =>
            array(
                'calle' => 'Calle Andrés de Urdaneta',
                'celular_contacto' => NULL,
                'ciudad' => 'ACAPULCO DE JUAREZ',
                'cobertura' => NULL,
                'codigo_postal' => '39355',
                'colonia' => 'FRACC HORNOS',
                'correo_contacto' => NULL,
                'created_at' => '2023-01-19 09:07:04',
                'id_old' => 63,
                'id_fiscale' => NULL,
                'nombre' => 'PAPAGAYO',
                'nombre_contacto' => 'Default',
                'objeto_descripcion' => NULL,
                'pagina_web' => 'https://hospitalpapagayo.com.mx/',
                'puesto_contacto' => NULL,
                'razon_social' => 'HOSPITAL PAPAGAYO',
                'rfc' => 'HPA0308089D4',
                'telefono' => '7444863300',
                'updated_at' => '2023-01-19 09:27:51',
            ),
            63 =>
            array(
                'calle' => 'BOULEVARD ADOLFO RUIZ CORTINES 3307',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcandía La Magdalena Contreras, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '10200',
                'colonia' => 'SAN JERONIMO LIDICE',
                'correo_contacto' => NULL,
                'created_at' => '2023-01-20 14:05:24',
                'id_old' => 64,
                'id_fiscale' => NULL,
                'nombre' => 'K2 SOLUCIONES TECNOLOGICAS',
                'nombre_contacto' => 'Default',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => NULL,
                'razon_social' => 'K2 SOLUCIONES TECNOLOGICAS',
                'rfc' => 'KST211015QL8',
                'telefono' => NULL,
                'updated_at' => '2023-01-20 14:33:56',
            ),
            64 =>
            array(
                'calle' => 'Avenida CONSTITUYENTES 1070',
                'celular_contacto' => NULL,
                'ciudad' => 'Alcandía Miguel Hidalgo, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '11950',
                'colonia' => 'Lomas Altas',
                'correo_contacto' => 'jesus.navarro@datawarden.com.mx',
                'created_at' => '2023-01-24 12:00:46',
                'id_old' => 65,
                'id_fiscale' => NULL,
                'nombre' => 'DATA WARDEN',
                'nombre_contacto' => 'Jesús Navarro',
                'objeto_descripcion' => 'Data Warden es una organización con un alto nivel de especialización en ciberseguridad, que con un equipo de expertos ampliamente experimentados apoya a sus clientes a lograr una adecuada gestión del riesgo tecnológico.',
                'pagina_web' => NULL,
                'puesto_contacto' => NULL,
                'razon_social' => 'Data Warden S.A. de C.V.',
                'rfc' => 'DWA041125U40',
                'telefono' => '53706270',
                'updated_at' => '2023-01-24 13:44:14',
            ),
            65 =>
            array(
                'calle' => 'Av. Puente Tecamachalco #26',
                'celular_contacto' => '5591985252',
                'ciudad' => 'Alcandía Miguel Hidalgo, CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '11000',
                'colonia' => 'Lomas de Chapultepec',
                'correo_contacto' => 'gcolina@fifomi.gob.mx',
                'created_at' => '2023-02-02 13:30:09',
                'id_old' => 66,
                'id_fiscale' => NULL,
                'nombre' => 'FIFOMI',
                'nombre_contacto' => 'Gustavo de la Colina Flores',
                'objeto_descripcion' => 'El Fideicomiso de Fomento Minero (FIFOMI) es una entidad paraestatal catalogada como fideicomiso público que forma parte del sistema financiero mexicano.',
                'pagina_web' => 'https://www.gob.mx/fifomi/',
                'puesto_contacto' => 'Gerente de Informática',
                'razon_social' => 'Nacional Financiera S.A.',
                'rfc' => 'FFM9002036F0',
                'telefono' => '52499500',
                'updated_at' => '2023-02-02 13:36:13',
            ),
            66 =>
            array(
                'calle' => 'Montecito 38 Piso 48',
                'celular_contacto' => NULL,
                'ciudad' => 'Benito Juárez, CDMX',
                'cobertura' => 'Nacional',
                'codigo_postal' => '03810',
                'colonia' => 'Nápoles',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-09 11:50:39',
                'id_old' => 67,
                'id_fiscale' => NULL,
                'nombre' => 'Grupo Adya',
                'nombre_contacto' => 'Adrián Enrique Sánchez Martínez',
                'objeto_descripcion' => 'Servicios profesionales de personal. supervisión, administración de nómina y capacitación de personas mismas que podrán aumentar o disminuir según las necesidades del cliente.',
                'pagina_web' => NULL,
                'puesto_contacto' => 'Apoderado Legal',
                'razon_social' => 'Grupo Adya Select, S. de R.L. de C.V',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2023-02-09 11:50:39',
            ),
            67 =>
            array(
                'calle' => 'Av. Insurgentes Sur No. 2453',
                'celular_contacto' => NULL,
                'ciudad' => 'Álvaro Obregón, CDMX',
                'cobertura' => 'Nacional',
                'codigo_postal' => '01090',
                'colonia' => 'Tizapán San Ángel',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-09 12:40:56',
                'id_old' => 68,
                'id_fiscale' => NULL,
                'nombre' => 'Mapfre',
                'nombre_contacto' => 'Ernesto Bobadilla Hernandez y José Antonio Gutiérrez Pinal',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Representante Legal.',
                'razon_social' => 'Mapfre Tepeyac, S.A de C.V',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2023-02-09 12:40:56',
            ),
            68 =>
            array(
                'calle' => 'Av. División del Norte No. 297',
                'celular_contacto' => NULL,
                'ciudad' => 'Benito Juárez, CDMX',
                'cobertura' => 'Internacional',
                'codigo_postal' => '03100',
                'colonia' => 'Del Valle',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-09 13:13:12',
                'id_old' => 69,
                'id_fiscale' => NULL,
                'nombre' => 'X Web',
                'nombre_contacto' => 'Rosina Eliuth Buelna Araujo',
                'objeto_descripcion' => 'Soluciones de TI',
                'pagina_web' => 'https://www.xweb.com.mx/',
                'puesto_contacto' => 'Apoderado Legal',
                'razon_social' => 'X Web, S.A de C.V',
                'rfc' => 'XWE0102149Q4',
                'telefono' => NULL,
                'updated_at' => '2023-02-09 13:13:52',
            ),
            69 =>
            array(
                'calle' => 'Av. Insurgentes Sur 1647 Piso 2',
                'celular_contacto' => NULL,
                'ciudad' => 'Benito Juárez',
                'cobertura' => NULL,
                'codigo_postal' => '03900',
                'colonia' => 'San José Insurgentes Sur',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-13 11:16:38',
                'id_old' => 70,
                'id_fiscale' => NULL,
                'nombre' => 'ARDUUS',
                'nombre_contacto' => 'Oscar Ramírez Flores',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'ARDUUS TI, S.C',
                'rfc' => 'ATI101123F26',
                'telefono' => NULL,
                'updated_at' => '2023-02-13 11:16:38',
            ),
            70 =>
            array(
                'calle' => 'Av. Paseo de la Reforma, Piso 22 265',
                'celular_contacto' => NULL,
                'ciudad' => 'Cuauhtemoc',
                'cobertura' => NULL,
                'codigo_postal' => '06500',
                'colonia' => 'Cuauhtemoc',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-13 12:16:30',
                'id_old' => 71,
                'id_fiscale' => NULL,
                'nombre' => 'Axtel',
                'nombre_contacto' => 'David Isarel Sánchez',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Jefe de Compras',
                'razon_social' => 'Axtel S.A.B de C.V',
                'rfc' => 'AXT940727FP8',
                'telefono' => NULL,
                'updated_at' => '2023-02-13 12:16:30',
            ),
            71 =>
            array(
                'calle' => 'Presidente Masaryk No. 61-901',
                'celular_contacto' => NULL,
                'ciudad' => 'Miguel Hidalgo',
                'cobertura' => 'Nacional',
                'codigo_postal' => '11560',
                'colonia' => 'Polanco',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-13 13:41:27',
                'id_old' => 72,
                'id_fiscale' => NULL,
                'nombre' => 'Becarios en Desarrollo, S.C',
                'nombre_contacto' => 'Miguel Macias Padilla',
                'objeto_descripcion' => 'Prestación de diversos servicios profesionales para las empresas en forma no exclusiva ni principal, que realiza a través de sus propios miembros, ya sean Asociados y/o miembros becarios a su cargo.',
                'pagina_web' => NULL,
                'puesto_contacto' => NULL,
                'razon_social' => 'Becarios en Desarrollo, S.C',
                'rfc' => 'BDE-050405-RR2',
                'telefono' => NULL,
                'updated_at' => '2023-02-13 13:41:27',
            ),
            72 =>
            array(
                'calle' => 'Av. Tolteca Poniente No. 2',
                'celular_contacto' => NULL,
                'ciudad' => 'Cuautlalcingo, Puebla',
                'cobertura' => 'Nacional',
                'codigo_postal' => '72735',
                'colonia' => 'Nuevo Humboldt',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-13 14:08:29',
                'id_old' => 73,
                'id_fiscale' => NULL,
                'nombre' => 'Colegio Humbolt',
                'nombre_contacto' => 'Norbert JÜrgen R. Weiss Wulf',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Apoderado Legal',
                'razon_social' => 'Colegio Humbolt, S.A de C.V',
                'rfc' => 'CHU840202R79',
                'telefono' => NULL,
                'updated_at' => '2023-02-13 14:08:29',
            ),
            73 =>
            array(
                'calle' => 'Mariano Otero No. 1105',
                'celular_contacto' => NULL,
                'ciudad' => 'Guadalajara',
                'cobertura' => 'Nacional',
                'codigo_postal' => '44530',
                'colonia' => 'Rinconada del bosque',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-13 16:00:17',
                'id_old' => 74,
                'id_fiscale' => NULL,
                'nombre' => 'Compusoluciones y Asociados',
                'nombre_contacto' => 'Vanessa Gómez Gónzalez',
                'objeto_descripcion' => 'Comercio al por mayor de equipo y accesorios de cómputo.',
                'pagina_web' => NULL,
                'puesto_contacto' => 'Apoderado Legal',
                'razon_social' => 'Compusoluciones y Asociados, S.A de C.V',
                'rfc' => 'CAS850526N64',
                'telefono' => NULL,
                'updated_at' => '2023-02-13 16:00:17',
            ),
            74 =>
            array(
                'calle' => 'Orquídeas Manzana 4, Casa 3,',
                'celular_contacto' => '0449511310121',
                'ciudad' => 'San Ándres Huayapam, Oaxaca',
                'cobertura' => NULL,
                'codigo_postal' => '68287',
                'colonia' => 'Fraccionamiento jardines de Huayapan',
                'correo_contacto' => 'escamilla_04@hotmail.com',
                'created_at' => '2023-02-14 12:46:43',
                'id_old' => 75,
                'id_fiscale' => NULL,
                'nombre' => 'LESLIE AIDE VARGAS PEREZ',
                'nombre_contacto' => 'Leslie Aide Vargas Pérez',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Arrendador',
                'razon_social' => 'LESLIE AIDE VARGAS PEREZ',
                'rfc' => 'VAPL700805K17',
                'telefono' => '0449511310121',
                'updated_at' => '2023-02-14 12:46:43',
            ),
            75 =>
            array(
                'calle' => 'n/a',
                'celular_contacto' => NULL,
                'ciudad' => 'n/a',
                'cobertura' => 'Nacional',
                'codigo_postal' => '0',
                'colonia' => 'n/a',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-14 13:00:02',
                'id_old' => 76,
                'id_fiscale' => NULL,
                'nombre' => 'Mavinco',
                'nombre_contacto' => 'Jesús Alberto Acosta Gónzalez',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Mavinco, S.A de C.V',
                'rfc' => NULL,
                'telefono' => NULL,
                'updated_at' => '2023-02-14 13:00:02',
            ),
            76 =>
            array(
                'calle' => 'Goldsmith No. 352',
                'celular_contacto' => NULL,
                'ciudad' => 'Miguel Hidalgo',
                'cobertura' => NULL,
                'codigo_postal' => '11540',
                'colonia' => 'Polanco III Sección',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-14 13:18:31',
                'id_old' => 77,
                'id_fiscale' => NULL,
                'nombre' => 'Strongbase',
                'nombre_contacto' => 'Ulises Jorge Alarcón',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Strongbase, S.A de C.V',
                'rfc' => 'STR091009K62',
                'telefono' => NULL,
                'updated_at' => '2023-02-14 13:18:31',
            ),
            77 =>
            array(
                'calle' => 'Aniceto Ortega No. 1314',
                'celular_contacto' => NULL,
                'ciudad' => 'Benito Juárez',
                'cobertura' => NULL,
                'codigo_postal' => '03100',
                'colonia' => 'Del Valle',
                'correo_contacto' => NULL,
                'created_at' => '2023-02-14 13:45:30',
                'id_old' => 78,
                'id_fiscale' => NULL,
                'nombre' => 'Wise Soluciones',
                'nombre_contacto' => 'Jorge Ernesto Cuéllar Martínez',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Wise Soluciones, S.A de C.V',
                'rfc' => 'WSO070403QP1',
                'telefono' => NULL,
                'updated_at' => '2023-02-14 13:45:30',
            ),
            78 =>
            array(
                'calle' => 'Av. Ejercito Nacional No. 350, Local 5B',
                'celular_contacto' => NULL,
                'ciudad' => 'Miguel Hidalgo',
                'cobertura' => 'Nacional',
                'codigo_postal' => '11560',
                'colonia' => 'Polanco V Sección',
                'correo_contacto' => 'martha.olguin@oxity.com',
                'created_at' => '2023-05-11 11:02:19',
                'id_old' => 81,
                'id_fiscale' => NULL,
                'nombre' => 'Axity',
                'nombre_contacto' => 'Martha Nohemi Olguín Gómez',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Representante Legal',
                'razon_social' => 'Axity México, S.A de C.V',
                'rfc' => 'ISC1204099L8',
                'telefono' => NULL,
                'updated_at' => '2023-05-11 11:02:19',
            ),
            79 =>
            array(
                'calle' => 'Calle Popotla S/N',
                'celular_contacto' => '7773306942',
                'ciudad' => 'Cuernavaca, Morelos',
                'cobertura' => NULL,
                'codigo_postal' => '62130',
                'colonia' => 'Tetela del Monte',
                'correo_contacto' => 'glo.gb@outlook.com',
                'created_at' => '2023-05-16 14:56:57',
                'id_old' => 82,
                'id_fiscale' => NULL,
                'nombre' => 'FLOY & LIPSON',
                'nombre_contacto' => 'Yessica Villeda',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => 'Comprador',
                'razon_social' => 'FLOY & LIPSON S.R.L DE C.V',
                'rfc' => 'FAL171018B26',
                'telefono' => '7773306942',
                'updated_at' => '2023-05-16 14:56:57',
            ),
            80 =>
            array(
                'calle' => 'INSURGENTES SUR 2435 PISO 4',
                'celular_contacto' => NULL,
                'ciudad' => 'CDMX',
                'cobertura' => NULL,
                'codigo_postal' => '01090',
                'colonia' => 'TIZAPAN SAN ÁNGEL',
                'correo_contacto' => 'lourdes.abadia@silent4business.com',
                'created_at' => '2023-08-14 16:21:33',
                'id_old' => 83,
                'id_fiscale' => NULL,
                'nombre' => 'Silent4business S.A. de C.V.',
                'nombre_contacto' => 'Lourdes del Pilar Abadía Velasco',
                'objeto_descripcion' => 'Multiproyectos',
                'pagina_web' => 'https://www.silent4business.com',
                'puesto_contacto' => 'Directora Jr. de Finanzas y Administración',
                'razon_social' => 'Silent4business S.A. de C.V.',
                'rfc' => 'SIL160727HV7',
                'telefono' => '5578233000',
                'updated_at' => '2023-08-14 17:26:15',
            ),
            81 =>
            array(
                'calle' => 'Av. Insurgentes Sur 2453',
                'celular_contacto' => NULL,
                'ciudad' => 'Álvaro Obregón',
                'cobertura' => NULL,
                'codigo_postal' => '01090',
                'colonia' => 'Tizapán San Ángel',
                'correo_contacto' => NULL,
                'created_at' => '2023-08-14 17:12:58',
                'id_old' => 84,
                'id_fiscale' => NULL,
                'nombre' => 'Silent4Business',
                'nombre_contacto' => 'SILENT4BUSINESS',
                'objeto_descripcion' => NULL,
                'pagina_web' => NULL,
                'puesto_contacto' => NULL,
                'razon_social' => 'Silent4Business',
                'rfc' => 'SIL160727HV7',
                'telefono' => NULL,
                'updated_at' => '2023-08-14 17:13:25',
            ),
        ));
    }
}
