<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProveedorOCSTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('proveedor_o_c_s')->delete();

        \DB::table('proveedor_o_c_s')->insert(array(
            0 =>
            array(
                'id' => 1,
                'nombre' => 'Proveedores Varios Nacionales',
                'razon_social' => 'Proveedores Varios Nacionales',
                'rfc' => 'N/A',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-09-19 16:27:12',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-09-19',
                'fecha_fin' => '2023-09-19',
            ),
            1 =>
            array(
                'id' => 2,
                'nombre' => 'FAR SYSTEMS',
                'razon_social' => 'FAR SYSTEMS S.C.P',
                'rfc' => 'FSY0501188U8',
                'contacto' => 'Miriam Valencia',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            2 =>
            array(
                'id' => 3,
                'nombre' => 'AURUM TECNOLOGIA',
                'razon_social' => 'Aurum Tecnología S.A de C.V',
                'rfc' => 'ATE130116Q28',
                'contacto' => 'Felipe Medina',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            3 =>
            array(
                'id' => 4,
                'nombre' => 'AXTEL',
                'razon_social' => 'AXTEL S.A.B. DE C.V.',
                'rfc' => 'AXT940727FP8',
                'contacto' => 'ANA CECILIA AGUIRRE GONZALEZ',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            4 =>
            array(
                'id' => 5,
                'nombre' => 'AyR',
                'razon_social' => 'AYR ENLACES EMPRESARIALES, S.A. DE C.V',
                'rfc' => 'AEE1605054P1',
                'contacto' => 'Lorena Piña Fuentes',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            5 =>
            array(
                'id' => 6,
                'nombre' => 'ContPAQi',
                'razon_social' => 'HUGO GONZALEZ GUERRA',
                'rfc' => 'GUGH791023DD0',
                'contacto' => 'MARIA CONSUELO TULE JIMENEZ',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            6 =>
            array(
                'id' => 7,
                'nombre' => 'MS NOTARIO',
                'razon_social' => 'MS NOTARIO S.C',
                'rfc' => 'MNO930107ST1',
                'contacto' => 'Sarahi Castaneda',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            7 =>
            array(
                'id' => 8,
                'nombre' => 'Notario 208',
                'razon_social' => 'N208 S.C',
                'rfc' => 'NXX1210186TA',
                'contacto' => 'Agustin Gutierrez Katze',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-28 09:22:03',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-28',
                'fecha_fin' => '2023-08-31',
            ),
            8 =>
            array(
                'id' => 9,
                'nombre' => 'Neixar MXN',
                'razon_social' => 'Neixar Systems S.A de C.V',
                'rfc' => 'NSY060512CS6',
                'contacto' => 'Guillermo Deloiza',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            9 =>
            array(
                'id' => 10,
                'nombre' => 'NOTARIA',
                'razon_social' => 'NOTARIA REFORMA 420 S.C.',
                'rfc' => 'NVE130306IT3',
                'contacto' => 'Lilia Reforma',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-29 19:14:59',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-29',
                'fecha_fin' => '2023-08-31',
            ),
            10 =>
            array(
                'id' => 11,
                'nombre' => 'OFFICE DEPOT',
                'razon_social' => 'OFFICE DEPOT DE MÉXICO S.A DE C.V',
                'rfc' => 'ODM950324V2A',
                'contacto' => 'Fabiola Pamela López Balbuena',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-09-25 16:36:15',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-09-25',
                'fecha_fin' => '2023-09-25',
            ),
            11 =>
            array(
                'id' => 12,
                'nombre' => 'Online MÉXICO',
                'razon_social' => 'Online Career Center MÉXICO S.API de C.V',
                'rfc' => 'OCC9611015V7',
                'contacto' => 'Beatriz Cardenas',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            12 =>
            array(
                'id' => 13,
                'nombre' => 'ESTRATEC',
                'razon_social' => 'ESTRATEC SA DE CV',
                'rfc' => 'EST850718Q51',
                'contacto' => 'LUIS KEN OHARA KONDO',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            13 =>
            array(
                'id' => 14,
                'nombre' => 'Zurich',
                'razon_social' => 'Zurich Cia de Seguros S.A.',
                'rfc' => 'ZSE950306M48',
                'contacto' => 'Claudine Seguros',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-09-06 11:03:38',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-18',
                'fecha_fin' => '2024-08-18',
            ),
            14 =>
            array(
                'id' => 15,
                'nombre' => 'PASE',
                'razon_social' => 'PASE, SERVICIOS ELECTRÓNICOS S.A DE C.V',
                'rfc' => 'ISD950921HE5',
                'contacto' => 'KaR.La Renta Michel Pacheco',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            15 =>
            array(
                'id' => 16,
                'nombre' => 'NUBAJ',
                'razon_social' => 'NUBAJ S.A. DE C.V.',
                'rfc' => 'NUB130904HN0',
                'contacto' => 'LYSETTE MAYEN SILVA',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            16 =>
            array(
                'id' => 17,
                'nombre' => 'Aseguradora Aserta SA de CV',
                'razon_social' => 'Aseguradora Aserta SA de CV',
                'rfc' => 'AAS9207314T7',
                'contacto' => 'ULISES RIVERA R',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            17 =>
            array(
                'id' => 18,
                'nombre' => 'COMERCIALIZADORA DE VALOR AGREGADO S.A DE C.V',
                'razon_social' => 'COMERCIALIZADORA DE VALOR AGREGADO S.A DE C.V',
                'rfc' => 'CVA9904266T9',
                'contacto' => 'Oscar Canales Contreras',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            18 =>
            array(
                'id' => 19,
                'nombre' => 'COMPUSOLUCIONES Y ASOCIADOS SA DE CV',
                'razon_social' => 'COMPUSOLUCIONES Y ASOCIADOS SA DE CV',
                'rfc' => 'CAS850526N64',
                'contacto' => 'Alejandra Real',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            19 =>
            array(
                'id' => 20,
                'nombre' => 'DKTM',
                'razon_social' => 'DKTM SC',
                'rfc' => 'DKV091106JI7',
                'contacto' => 'SONIA FERNANDEZ',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            20 =>
            array(
                'id' => 21,
                'nombre' => 'GRUPO DICE SA DE CV',
                'razon_social' => 'GRUPO DICE SA DE CV',
                'rfc' => 'GDI880315IYA',
                'contacto' => 'SANDRA BERROETA',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-14 16:55:06',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-14',
                'fecha_fin' => '2023-08-15',
            ),
            21 =>
            array(
                'id' => 22,
                'nombre' => 'INGRAM',
                'razon_social' => 'INGRAM MICRO MEXICO, S.A. DE C.V',
                'rfc' => 'IMM9304016Z4',
                'contacto' => 'GILBERTO NANCO',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            22 =>
            array(
                'id' => 23,
                'nombre' => 'MAAT',
                'razon_social' => 'Maat Asesores SC',
                'rfc' => 'MAS171023M71',
                'contacto' => 'JORGE A. FERNÁNDEZ I.',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            23 =>
            array(
                'id' => 24,
                'nombre' => 'MAPS',
                'razon_social' => 'MAYORISTAS DE PARTES Y SERVICIOS .SA de C.V',
                'rfc' => 'MPS920227IL9',
                'contacto' => 'Elsa Gallegos',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-16 19:53:15',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-16',
                'fecha_fin' => '2023-08-21',
            ),
            24 =>
            array(
                'id' => 25,
                'nombre' => 'ORBEN',
                'razon_social' => 'ORBEN COMUNICACIONES SAPI DE CV',
                'rfc' => 'OCO9804024E6',
                'contacto' => 'Flor Cedeño Plascencia',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            25 =>
            array(
                'id' => 26,
                'nombre' => 'WESTCON',
                'razon_social' => 'WESTCON MEXICO S.A DE C.V',
                'rfc' => 'WME000218GK3',
                'contacto' => 'RAUL NAVARRO',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            26 =>
            array(
                'id' => 27,
                'nombre' => 'WISE',
                'razon_social' => 'WISE SOLUTIONS SA DE CV',
                'rfc' => 'WSO070403QP1',
                'contacto' => 'Jorge Ernesto Cuéllar Martínez',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            27 =>
            array(
                'id' => 28,
                'nombre' => 'X WEB',
                'razon_social' => 'X WEB SA DE CV',
                'rfc' => 'XWE0102149Q4',
                'contacto' => 'Edgardo Calderón',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            28 =>
            array(
                'id' => 29,
                'nombre' => 'XALINA',
                'razon_social' => 'JUAN RAMON CHAN AQUINO',
                'rfc' => 'CAAJ7409038M9',
                'contacto' => 'Juan Ramon Chan Aquino',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            29 =>
            array(
                'id' => 30,
                'nombre' => 'VAINDEC',
                'razon_social' => 'Vaindec SA de CV',
                'rfc' => 'VAI1409222H1',
                'contacto' => 'Herman Rosso',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            30 =>
            array(
                'id' => 31,
                'nombre' => 'BMP CPNSULTORES',
                'razon_social' => 'BMP CONSULTORES SA DE CV',
                'rfc' => 'BCO140411M76',
                'contacto' => 'Vista Linda',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            31 =>
            array(
                'id' => 32,
                'nombre' => 'KAIZEN',
                'razon_social' => 'Kaizen Soluciones TIC, S.A. de C.V.',
                'rfc' => 'KST150518K37',
                'contacto' => 'Arturo García-Naranjo y Cinca',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            32 =>
            array(
                'id' => 33,
                'nombre' => 'ADMI PROCESOS',
                'razon_social' => 'ADMINISTRACION DE PROCESOS DE TRANSFORMACION',
                'rfc' => 'APT050613TQ6',
                'contacto' => 'Lorena Pina',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            33 =>
            array(
                'id' => 34,
                'nombre' => 'CESCE FIANZAS',
                'razon_social' => 'CESCE FIANZAS MEXICO SA DE CV',
                'rfc' => 'CFM1008302NA',
                'contacto' => 'Victor Vargas',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-29 11:42:59',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-24',
                'fecha_fin' => '2023-12-31',
            ),
            34 =>
            array(
                'id' => 35,
                'nombre' => 'Ortiz Linares',
                'razon_social' => 'Ortiz Linares Abogados Asociados S C',
                'rfc' => 'OLA121130DG7',
                'contacto' => 'Miguel Angel Linares',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            35 =>
            array(
                'id' => 36,
                'nombre' => 'SACRESA',
                'razon_social' => 'Sacresa Consultores SA de CV',
                'rfc' => 'SCO1103166EA',
                'contacto' => 'Angeles Garcia',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            36 =>
            array(
                'id' => 37,
                'nombre' => 'JACQUES',
                'razon_social' => 'SERVICIOS DE CONSULTORIA JURIDICA JACQUES FONTAINE S DE R.L D',
                'rfc' => 'SCJ150226HCA',
                'contacto' => 'Ariadna Aguilar',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            37 =>
            array(
                'id' => 38,
                'nombre' => 'Rayn Tech',
                'razon_social' => 'Rayn Tech SA de CV',
                'rfc' => 'RTE160922F37',
                'contacto' => 'Miriam Klein',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            38 =>
            array(
                'id' => 39,
                'nombre' => 'CONSEIL D AFFAIRES BELAYAGE SA DE CV',
                'razon_social' => 'CONSEIL D AFFAIRES BELAYAGE SA DE CV',
                'rfc' => 'CDA160427NP3',
                'contacto' => 'JENNY RIVERA',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            39 =>
            array(
                'id' => 40,
                'nombre' => 'Cyberpuerta SA de CV',
                'razon_social' => 'Cyberpuerta SA de CV',
                'rfc' => 'CYB080602ISA',
                'contacto' => 'Oscar Joaquin Gutierrez',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-09-21 13:46:23',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-09-21',
                'fecha_fin' => '2023-09-21',
            ),
            40 =>
            array(
                'id' => 41,
                'nombre' => 'Estrategias BETA S.C.',
                'razon_social' => 'Estrategias BETA S.C.',
                'rfc' => 'EBE121221671',
                'contacto' => 'Serafin Lugo Martinez',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            41 =>
            array(
                'id' => 42,
                'nombre' => 'CFE SUMINISTRADOR DE SERVICIOS BASICOS',
                'razon_social' => 'CFE SUMINISTRADOR DE SERVICIOS BASICOS',
                'rfc' => 'CSS160330CP7',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            42 =>
            array(
                'id' => 43,
                'nombre' => 'BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BANCA MULTIPLE GRUPO FINANCIERO BANORTE',
                'razon_social' => 'BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BANCA MULTIPLE GRUPO FINANCIERO BANORTE',
                'rfc' => 'BMN930209927',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            43 =>
            array(
                'id' => 44,
                'nombre' => 'DCH Global SA de CV',
                'razon_social' => 'DCH Global SA de CV',
                'rfc' => 'DGL151201382',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            44 =>
            array(
                'id' => 45,
                'nombre' => 'ANCIANO Y AYALA ABOGADOS, S.C.',
                'razon_social' => 'ANCIANO Y AYALA ABOGADOS, S.C.',
                'rfc' => 'AAA070921TB9',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            45 =>
            array(
                'id' => 46,
                'nombre' => 'TELEFONOS DE MEXICO S.A.B. DE C.V.',
                'razon_social' => 'TELEFONOS DE MEXICO S.A.B. DE C.V.',
                'rfc' => 'TME840315KT6',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            46 =>
            array(
                'id' => 47,
                'nombre' => 'APPLE',
                'razon_social' => 'APPLE OPERATIONS MEXICO SA DE CV',
                'rfc' => 'AOM920820BEA',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            47 =>
            array(
                'id' => 48,
                'nombre' => 'FREIGHT IDEAS SA DE CV',
                'razon_social' => 'FREIGHT IDEAS SA DE CV',
                'rfc' => 'FID080111867',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            48 =>
            array(
                'id' => 49,
                'nombre' => 'GLOBAL STD',
                'razon_social' => 'GLOBAL STANDARDS S.C',
                'rfc' => 'GST080421UT4',
                'contacto' => 'Tatiana Jerónimo',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            49 =>
            array(
                'id' => 50,
                'nombre' => 'NOTARIA 201 S.C.',
                'razon_social' => 'NOTARIA 201 S.C.',
                'rfc' => 'NDU161018QEA',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            50 =>
            array(
                'id' => 51,
                'nombre' => 'DELETE TECNOLOGY, SA DE CV',
                'razon_social' => 'DELETE TECNOLOGY, SA DE CV',
                'rfc' => 'SBL1008258T0',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            51 =>
            array(
                'id' => 52,
                'nombre' => 'Servicios en Limpieza y Mantenimiento DANFER SA de CV',
                'razon_social' => 'Servicios en Limpieza y Mantenimiento DANFER SA de CV',
                'rfc' => 'SLM121017V35',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            52 =>
            array(
                'id' => 53,
                'nombre' => 'GBT TRAVEL SERVICES MEXICO S DE RL DE CV',
                'razon_social' => 'GBT TRAVEL SERVICES MEXICO S DE RL DE CV',
                'rfc' => 'GTS131114AL9',
                'contacto' => 'MELISSA MORLET',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            53 =>
            array(
                'id' => 54,
                'nombre' => 'AFH CONSULTORES Y ASOCIADOS S.C.',
                'razon_social' => 'AFH CONSULTORES Y ASOCIADOS S.C.',
                'rfc' => 'AFH9301258P2',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            54 =>
            array(
                'id' => 55,
                'nombre' => 'UNIVERSIDAD DE LAS AMERICAS, A.C.',
                'razon_social' => 'UNIVERSIDAD DE LAS AMERICAS, A.C.',
                'rfc' => 'UAM630613SM7',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            55 =>
            array(
                'id' => 56,
                'nombre' => 'LAS MEJORES EMPRESAS PARA TRABAJAR SAPI DE CV',
                'razon_social' => 'LAS MEJORES EMPRESAS PARA TRABAJAR SAPI DE CV',
                'rfc' => 'GPT030828U24',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            56 =>
            array(
                'id' => 57,
                'nombre' => 'COMUNICACIÓN INTELIGENTE CBM SA DE CV',
                'razon_social' => 'COMUNICACIÓN INTELIGENTE CBM SA DE CV',
                'rfc' => 'CIC161018JC8',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            57 =>
            array(
                'id' => 58,
                'nombre' => 'AF SERVICIOS SGMM',
                'razon_social' => 'AF SERVICIOS SGMM SA DE CV',
                'rfc' => 'XAX010101000',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            58 =>
            array(
                'id' => 59,
                'nombre' => 'FUNDACIÓN POLITECNICO',
                'razon_social' => 'FUNDACIÓN POLITECNICO AC',
                'rfc' => 'FPO960828SY0',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            59 =>
            array(
                'id' => 60,
                'nombre' => 'FARCIERT',
                'razon_social' => 'FARCIERT FLORES Y CIA SC',
                'rfc' => 'FFL901019NM9',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            60 =>
            array(
                'id' => 61,
                'nombre' => 'DHL EXPRESS MEXICO S.A. DE C.V.',
                'razon_social' => 'DHL EXPRESS MEXICO S.A. DE C.V.',
                'rfc' => 'DEM8801152E9',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-09-20 13:05:46',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-09-20',
                'fecha_fin' => '2023-09-20',
            ),
            61 =>
            array(
                'id' => 62,
                'nombre' => 'OPERADORA OMX S.A. DE C.V.',
                'razon_social' => 'OPERADORA OMX S.A. DE C.V.',
                'rfc' => 'OOM960429832',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            62 =>
            array(
                'id' => 63,
                'nombre' => 'HDI SEGUROS SA DE CV',
                'razon_social' => 'HDI SEGUROS SA DE CV',
                'rfc' => 'HSE701218532',
                'contacto' => 'Margarita Garcia Quiroz',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-08-25 12:07:38',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-25',
                'fecha_fin' => '2023-08-25',
            ),
            63 =>
            array(
                'id' => 64,
                'nombre' => 'ASOCIACIÓN NACIONAL DE UNIVERSIDADES E INSTITUCIONES DE EDUCACIÓN SUPERIOR DE LA REPÚBLICA MEXICANA',
                'razon_social' => 'ASOCIACIÓN NACIONAL DE UNIVERSIDADES E INSTITUCIONES DE EDUCACIÓN SUPERIOR DE LA REPÚBLICA MEXICANA',
                'rfc' => 'ANU930617MQ5',
                'contacto' => 'FROYLÁN LÓPEZ VALENCIA',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            64 =>
            array(
                'id' => 65,
                'nombre' => 'Avelina Mayela Ramirez Rivera',
                'razon_social' => 'Avelina Mayela Ramirez Rivera',
                'rfc' => 'RARA701016BJ5',
                'contacto' => 'MAYELA RAMIREZ RIVERA',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            65 =>
            array(
                'id' => 66,
                'nombre' => 'UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO',
                'razon_social' => 'UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO',
                'rfc' => 'UNA2907227Y5',
                'contacto' => 'Lic. Yazmin Barrales Zarza',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            66 =>
            array(
                'id' => 67,
                'nombre' => 'RADIOMOVIL DIPSA SA DE CV',
                'razon_social' => 'RADIOMOVIL DIPSA SA DE CV',
                'rfc' => 'RDI841003QJ4',
                'contacto' => 'ITZHEL MOUEL OVIEDO',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            67 =>
            array(
                'id' => 68,
                'nombre' => 'Asociación Mexicana de Lucha Contra el Cáncer A.C.',
                'razon_social' => 'Asociación Mexicana de Lucha Contra el Cáncer A.C.',
                'rfc' => 'AML7204246A1',
                'contacto' => 'Araceli Carreto Ortíz',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            68 =>
            array(
                'id' => 69,
                'nombre' => 'AMERICAN EXPRESS COMPANY (MEXICO), S.A. DE C.V.',
                'razon_social' => 'AMERICAN EXPRESS COMPANY (MEXICO), S.A. DE C.V.',
                'rfc' => 'aec810901298',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            69 =>
            array(
                'id' => 70,
                'nombre' => 'SOCIEDAD PANAMERICANA DE ESTUDIOS EMPRESARIALES, A.C.',
                'razon_social' => 'SOCIEDAD PANAMERICANA DE ESTUDIOS EMPRESARIALES, A.C.',
                'rfc' => 'spe661112kj4',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            70 =>
            array(
                'id' => 71,
                'nombre' => 'ANTONIO ROSADO SÁNCHEZ',
                'razon_social' => 'ANTONIO ROSADO SÁNCHEZ',
                'rfc' => 'rosa381127qh2',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            71 =>
            array(
                'id' => 72,
                'nombre' => 'INTELICOMP S.A DE C.V',
                'razon_social' => 'INTELICOMP S.A DE C.V',
                'rfc' => 'INT031028KA5',
                'contacto' => 'JESUS JOSUE VALENCIA GARCIA',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            72 =>
            array(
                'id' => 73,
                'nombre' => 'CHUBB',
                'razon_social' => 'CHUBB SEGUROS MEXICO SA',
                'rfc' => 'ASE901221SM4',
                'contacto' => 'N/A',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            73 =>
            array(
                'id' => 74,
                'nombre' => 'INSTITUTO SUPERIOR DE ESTUDIOS FISCALES A.C.',
                'razon_social' => 'INSTITUTO SUPERIOR DE ESTUDIOS FISCALES A.C.',
                'rfc' => 'ISE751222215',
                'contacto' => 'Vianey Osorio Olivera',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            74 =>
            array(
                'id' => 75,
                'nombre' => 'Soluciones Integrales en Capacitación S.A. de C.V.',
                'razon_social' => 'Soluciones Integrales en Capacitación S.A. de C.V.',
                'rfc' => 'SIC980401K73',
                'contacto' => 'Ingrid Dayeli Colin Sanabria',
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            75 =>
            array(
                'id' => 76,
                'nombre' => 'JUAN CARLOS SUMANO CARREÑO',
                'razon_social' => 'JUAN CARLOS SUMANO CARREÑO',
                'rfc' => 'SUCJ761124NK1',
                'contacto' => 'Juan Carlos Sumano',
                'estado' => 0,
                'created_at' => '2023-08-21 10:45:16',
                'updated_at' => '2023-08-21 10:45:16',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            76 =>
            array(
                'id' => 77,
                'nombre' => 'Certification Hub México S.C',
                'razon_social' => 'Certification Hub México S.C',
                'rfc' => 'CHM141101DQ5',
                'contacto' => 'Charis Segovia',
                'estado' => 0,
                'created_at' => '2023-08-21 16:40:51',
                'updated_at' => '2023-08-21 16:42:58',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-22',
                'fecha_fin' => '2023-08-25',
            ),
            77 =>
            array(
                'id' => 78,
                'nombre' => 'NYCE',
                'razon_social' => 'NORMALIZACIÓN Y CERTIFICACIÓN NYCE S.C.',
                'rfc' => 'NCE941107Q87',
                'contacto' => 'FABIOLA CORREA LEDESMA',
                'estado' => 0,
                'created_at' => '2023-08-28 16:20:54',
                'updated_at' => '2023-08-30 13:09:56',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-30',
                'fecha_fin' => '2023-08-31',
            ),
            78 =>
            array(
                'id' => 79,
                'nombre' => 'SOLUCIONES, ANALITICOS Y SERVICIOS TEAM S.A P.I DE C.V',
                'razon_social' => 'SOLUCIONES, ANALITICOS Y SERVICIOS TEAM S.A P.I DE C.V',
                'rfc' => 'SAS160825EQ3',
                'contacto' => 'SHAULA VIVIAN MENDOZA GAULT',
                'estado' => 0,
                'created_at' => '2023-08-30 17:09:04',
                'updated_at' => '2023-08-31 15:06:56',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-08-31',
                'fecha_fin' => '2023-08-31',
            ),
            79 =>
            array(
                'id' => 80,
                'nombre' => 'IMAGEN TI',
                'razon_social' => 'IMAGEN TI, S.A. DE C.V.',
                'rfc' => 'ITI121211AE2',
                'contacto' => 'MANUEL ALEJANDRE RAMIREZ',
                'estado' => 0,
                'created_at' => '2023-08-30 17:32:39',
                'updated_at' => '2023-08-30 17:32:39',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            80 =>
            array(
                'id' => 81,
                'nombre' => 'TEAM',
                'razon_social' => 'TECNOLOGIA ESPECIALIZADA ASOCIADA DE MEXICO S.A. DE C.V.',
                'rfc' => 'TEA950619MP8',
                'contacto' => 'José Antonio Gutiérrez González',
                'estado' => 0,
                'created_at' => '2023-09-04 18:55:00',
                'updated_at' => '2023-09-21 12:51:15',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-09-21',
                'fecha_fin' => '2023-09-21',
            ),
            81 =>
            array(
                'id' => 82,
                'nombre' => 'LIVIJO',
                'razon_social' => 'José Esquivel Rosales',
                'rfc' => 'EURJ851128P28',
                'contacto' => 'José Esquivel',
                'estado' => 0,
                'created_at' => '2023-09-06 10:50:04',
                'updated_at' => '2023-09-22 16:42:33',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => '2023-09-22',
                'fecha_fin' => '2023-09-22',
            ),
            82 =>
            array(
                'id' => 83,
                'nombre' => 'Pancita Doña Olga',
                'razon_social' => 'MARIA DEL CARMEN RODRIGUEZ GOMEZ',
                'rfc' => 'ROGC710629T82',
                'contacto' => 'FRANCISCO RODRIGUEZ GOMEZ  TEL. 7771345037',
                'estado' => 0,
                'created_at' => '2023-09-19 16:24:47',
                'updated_at' => '2023-09-19 16:24:47',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            83 =>
            array(
                'id' => 84,
                'nombre' => 'Heydi Velarte Tapia',
                'razon_social' => 'Heydi Velarte Tapia',
                'rfc' => 'VETH7809274D1',
                'contacto' => 'Pepe Velarde',
                'estado' => 0,
                'created_at' => '2023-09-19 16:32:02',
                'updated_at' => '2023-09-19 16:32:02',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            84 =>
            array(
                'id' => 85,
                'nombre' => 'JUAN ISRAEL GONZALEZ MURILLO',
                'razon_social' => 'JUAN ISRAEL GONZALEZ MURILLO',
                'rfc' => 'GOMJ8002025F1',
                'contacto' => 'Drink Truck / Tel. 55 2727 4234',
                'estado' => 0,
                'created_at' => '2023-09-19 16:39:09',
                'updated_at' => '2023-09-19 16:39:09',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            85 =>
            array(
                'id' => 86,
                'nombre' => 'ERICK ALANIZ MORALES',
                'razon_social' => 'ERICK ALANIZ MORALES',
                'rfc' => 'AAME880718AYA',
                'contacto' => '777 225 1549',
                'estado' => 0,
                'created_at' => '2023-09-19 16:58:49',
                'updated_at' => '2023-09-19 16:58:49',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
            86 =>
            array(
                'id' => 87,
                'nombre' => 'AMAZON DE MÉXICO',
                'razon_social' => 'AMAZON DE MÉXICO',
                'rfc' => 'MAL181128TA6',
                'contacto' => 'n/a',
                'estado' => 0,
                'created_at' => '2023-09-27 13:36:47',
                'updated_at' => '2023-09-27 13:36:47',
                'deleted_at' => NULL,
                'facturacion' => NULL,
                'direccion' => NULL,
                'envio' => NULL,
                'credito' => NULL,
                'fecha_inicio' => NULL,
                'fecha_fin' => NULL,
            ),
        ));
    }
}
