FROM mcuadros/ofelia:latest

# Copy the Ofelia configuration file to the container
COPY run_queues_worker.sh run_queues_worker.sh

# Set execution permissions for the configuration file
RUN chmod +x run_queues_worker.sh
