global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter-tabantaj:9121']

  # prometheus-nginx-exporter
  - job_name: nginx-exporter
    static_configs:
      - targets: ['nginx-exporter-tabantaj:9113']

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter-tabantaj:9187"]

  - job_name: prometheus-node-exporter-tabantaj
    static_configs:
      - targets: ['prometheus-node-exporter-tabantaj:9100']

  - job_name: logstash-exporter-tabantaj
    static_configs:
      - targets: ['logstash-exporter-tabantaj:5044']

  - job_name: elastic-exporter-tabantaj
    static_configs:
      - targets: ['elastic-exporter-tabantaj:9200']

  # - job_name: cadvisor-exporter-tabantaj
  #   static_configs:
  #     - targets: ['cadvisor-exporter-tabantaj:8081']
