<?php

namespace App\Models;

use AlterCuestionarioRecibeInformacionTable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AnalisisAIA extends Model
{
    use HasFactory;


    public $table = 'analisis_aia';

    const TipoServerSelect = [
        '1' => 'Físico',
        '2' => 'Virtual',

    ];
    const TipoAccesoSelect = [
        '1' => 'WEB',
        '2' => 'Cliente-Servidor',
        '3' => 'N/a',

    ];

    const TipoCertificadoSelect = [
        '1' => 'Sí',
        '2' => 'No',
        '3' => 'N/a',

    ];

    const TipoInternetSelect = [
        '1' => 'Sí',
        '2' => 'No',
        '3' => 'N/a',

    ];

    public $fillable = [

        'id',
        'fecha_entrevista',
        'entrevistado',
        'puesto',
        'area',
        'direccion',
        'extencion',
        'correo',
        'aplicaciones_a_cargo',
        // DATOS DE IDENTIFICACIÓN DEL PROCESO
        'id_aplicacion',
        'nombre_aplicacion',
        'version',
        'tipo',
        'objetivo_aplicacion',
        'periodicidad',
        'p_otro_txt',
        'area_pertenece_aplicacion',
        'area_responsable_aplicacion',
        // RESPONSABLES DEL PROCESO
        'titular_nombre',
        'titular_a_paterno',
        'titular_a_materno',
        'titular_puesto',
        'titular_correo',
        'titular_extencion',
        'suplente_nombre',
        'suplente_a_paterno',
        'suplente_a_materno',
        'suplente_puesto',
        'suplente_correo',
        'suplente_extencion',
        'supervisor_nombre',
        'supervisor_a_paterno',
        'supervisor_a_materno',
        'supervisor_puesto',
        'supervisor_correo',
        'supervisor_extencion',
        // FLUJO DEL PROCESO
        'flujo_q_1',
        'flujo_q_2',
        'flujo_q_5',

        //INFRAESTRUCTURA TECNOLÓGICA
        'app_ip',
        'bd_ip',
        'otro_ip',
        'app_host',
        'bd_host',
        'otro_host',
        'app_base',
        'bd_base',
        'otro_base',
        'app_puerto',
        'bd_puerto',
        'otro_puerto',
        'app_servidor',
        'bd_servidor',
        'otro_servidor',
        'app_SO',
        'bd_SO',
        'otro_SO',
        'app_acceso',
        'bd_acceso',
        'otro_acceso',
        'app_url',
        'bd_url',
        'otro_url',
        'app_ip_publica',
        'bd_ip_publica',
        'otro_ip_publica',
        'app_certificado',
        'bd_certificado',
        'otro_certificado',
        'app_tipo_cifrado',
        'bd_tipo_cifrado',
        'otro_tipo_cifrado',
        'app_internet',
        'bd_internet',
        'otro_internet',
        'app_datos_url',
        'bd_datos_url',
        'otro_datos_url',
        'app_acceso_moviles',
        'bd_acceso_moviles',
        'otro_acceso_moviles',
        'app_nombre_app_movil',
        'bd_nombre_app_movil',
        'otro_nombre_app_movil',
        'app_interaccion_otras_apps',
        'bd_interaccion_otras_apps',
        'otro_interaccion_otras_apps',
        'app_datos_interactuan',
        'bd_datos_interactuan',
        'otro_datos_interactuan',
        'app_soporte_terceros',
        'bd_soporte_terceros',
        'otro_soporte_terceros',
        'app_datos_terceros',
        'bd_datos_terceros',
        'otro_datos_terceros',
        'app_instancia_balanceo',
        'bd_instancia_balanceo',
        'otro_instancia_balanceo',
        'app_datos_balanceo',
        'bd_datos_balanceo',
        'otro_datos_balanceo',
        'app_sofware_adicional',
        'bd_sofware_adicional',
        'otro_sofware_adicional',
        'app_lenguajes',
        'bd_lenguajes',
        'otro_lenguajes',
        'contingencia_app_ip',
        'contingencia_bd_ip',
        'contingencia_otro_ip',
        'contingencia_app_host',
        'contingencia_bd_host',
        'contingencia_otro_host',
        'contingencia_app_servidor',
        'contingencia_bd_servidor',
        'contingencia_otro_servidor',
        'contingencia_app_SO',
        'contingencia_bd_SO',
        'contingencia_otro_SO',
        'contingencia_app_acceso',
        'contingencia_bd_acceso',
        'contingencia_otro_acceso',
        'contingencia_app_url',
        'contingencia_bd_url',
        'contingencia_otro_url',
        // PERÍODOS CRÍTICOS
        'primer_semestre',
        'segundo_semestre',
        'ene',
        'feb',
        'mar',
        'abr',
        'may',
        'jun',
        'jul',
        'ago',
        'sep',
        'oct',
        'nov',
        'dic',
        's1',
        's2',
        's3',
        's4',
        'd1',
        'd2',
        'd3',
        'd4',
        'd5',
        'd6',
        'd7',
        'd8',
        'd9',
        'd10',
        'd11',
        'd12',
        'd13',
        'd14',
        'd15',
        'd16',
        'd17',
        'd18',
        'd19',
        'd20',
        'd21',
        'd22',
        'd23',
        'd24',
        'd25',
        'd26',
        'd27',
        'd28',
        'd29',
        'd30',
        'd31',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'h7',
        'h8',
        'h9',
        'h10',
        'h11',
        'h12',
        'h13',
        'h14',
        'h15',
        'h16',
        'h17',
        'h18',
        'h19',
        'h20',
        'h21',
        'h22',
        'h23',
        'h24',
        // TIEMPOS DE RECUPERACIÓN
        'rpo_mes',
        'rpo_semana',
        'rpo_dia',
        'rpo_hora',
        'rto_mes',
        'rto_semana',
        'rto_dia',
        'rto_hora',
        'wrt_mes',
        'wrt_semana',
        'wrt_dia',
        'wrt_hora',
        'mtpd_mes',
        'mtpd_semana',
        'mtpd_dia',
        'mtpd_hora',
        // RESPALDOS DE INFORMACIÓN
        'respaldo_q_14',
        'respaldo_q_15',
        'respaldo_q_16',

        // PROBABILIDAD DE INCIDENTES DISRUPTIVOS
        'disruptivos_q_1',
        'disruptivos_q_2',
        'disruptivos_q_3',
        'disruptivos_q_4',
        'disruptivos_q_5',
        'disruptivos_q_6',
        'disruptivos_q_7',
        'disruptivos_q_8',
        'disruptivos_q_9',
        'disruptivos_q_10',
        'disruptivos_q_11',
        // RIESGOS E INCIDENTES DISRUPTIVOS
        'operacion_q_1',
        'operacion_q_2',
        'operacion_q_3',
        'regulatorio_q_1',
        'regulatorio_q_2',
        'regulatorio_q_3',
        'reputacion_q_1',
        'reputacion_q_2',
        'reputacion_q_3',
        'social_q_1',
        'social_q_2',
        'social_q_3',
        'incidentes_q_26',
        'incidentes_q_27',
        'q_19',
        // Firmas
        'firma_Entrevistado',
        'firma_Jefe',
        'firma_Entrevistador',
        'exite_firma_Entrevistado',
        'exite_firma_Jefe',
        'exite_firma_Entrevistador',

    ];

    public function proporcionaInformacion()
    {
        return $this->hasMany(CuestionarioProporcionaInformacionAIA::class, 'cuestionario_id');
    }

    public function proporcionaMantenimientos()
    {
        return $this->hasMany(LiberaMantenimientoAIA::class, 'cuestionario_id');
    }
}
